
package com.amazon.webservices.awsecommerceservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.1.16
 * 2018-10-05T17:30:35.263+05:30
 * Generated source version: 3.1.16
 * 
 */
public final class AWSECommerceServicePortType_AWSECommerceServicePortFR_Client {

    private static final QName SERVICE_NAME = new QName("http://webservices.amazon.com/AWSECommerceService/2011-08-01", "AWSECommerceService");

    private AWSECommerceServicePortType_AWSECommerceServicePortFR_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = AWSECommerceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        AWSECommerceService ss = new AWSECommerceService(wsdlURL, SERVICE_NAME);
        AWSECommerceServicePortType port = ss.getAWSECommerceServicePortFR();  
        
        {
        System.out.println("Invoking cartCreate...");
        com.amazon.webservices.awsecommerceservice.CartCreate _cartCreate_body = new com.amazon.webservices.awsecommerceservice.CartCreate();
        _cartCreate_body.setMarketplaceDomain("MarketplaceDomain1168135502");
        _cartCreate_body.setAWSAccessKeyId("AWSAccessKeyId1982710427");
        _cartCreate_body.setAssociateTag("AssociateTag-1318741080");
        _cartCreate_body.setValidate("Validate-2131954799");
        _cartCreate_body.setXMLEscaping("XMLEscaping-504392476");
        com.amazon.webservices.awsecommerceservice.CartCreateRequest _cartCreate_bodyShared = new com.amazon.webservices.awsecommerceservice.CartCreateRequest();
        _cartCreate_bodyShared.setMergeCart("MergeCart1012028642");
        com.amazon.webservices.awsecommerceservice.CartCreateRequest.Items _cartCreate_bodySharedItems = new com.amazon.webservices.awsecommerceservice.CartCreateRequest.Items();
        java.util.List<com.amazon.webservices.awsecommerceservice.CartCreateRequest.Items.Item> _cartCreate_bodySharedItemsItem = new java.util.ArrayList<com.amazon.webservices.awsecommerceservice.CartCreateRequest.Items.Item>();
        _cartCreate_bodySharedItems.getItem().addAll(_cartCreate_bodySharedItemsItem);
        _cartCreate_bodyShared.setItems(_cartCreate_bodySharedItems);
        java.util.List<java.lang.String> _cartCreate_bodySharedResponseGroup = new java.util.ArrayList<java.lang.String>();
        java.lang.String _cartCreate_bodySharedResponseGroupVal1 = "_cartCreate_bodySharedResponseGroupVal-146506349";
        _cartCreate_bodySharedResponseGroup.add(_cartCreate_bodySharedResponseGroupVal1);
        _cartCreate_bodyShared.getResponseGroup().addAll(_cartCreate_bodySharedResponseGroup);
        _cartCreate_body.setShared(_cartCreate_bodyShared);
        java.util.List<com.amazon.webservices.awsecommerceservice.CartCreateRequest> _cartCreate_bodyRequest = new java.util.ArrayList<com.amazon.webservices.awsecommerceservice.CartCreateRequest>();
        com.amazon.webservices.awsecommerceservice.CartCreateRequest _cartCreate_bodyRequestVal1 = new com.amazon.webservices.awsecommerceservice.CartCreateRequest();
        _cartCreate_bodyRequestVal1.setMergeCart("MergeCart2003434888");
        com.amazon.webservices.awsecommerceservice.CartCreateRequest.Items _cartCreate_bodyRequestVal1Items = new com.amazon.webservices.awsecommerceservice.CartCreateRequest.Items();
        java.util.List<com.amazon.webservices.awsecommerceservice.CartCreateRequest.Items.Item> _cartCreate_bodyRequestVal1ItemsItem = new java.util.ArrayList<com.amazon.webservices.awsecommerceservice.CartCreateRequest.Items.Item>();
        _cartCreate_bodyRequestVal1Items.getItem().addAll(_cartCreate_bodyRequestVal1ItemsItem);
        _cartCreate_bodyRequestVal1.setItems(_cartCreate_bodyRequestVal1Items);
        java.util.List<java.lang.String> _cartCreate_bodyRequestVal1ResponseGroup = new java.util.ArrayList<java.lang.String>();
        _cartCreate_bodyRequestVal1.getResponseGroup().addAll(_cartCreate_bodyRequestVal1ResponseGroup);
        _cartCreate_bodyRequest.add(_cartCreate_bodyRequestVal1);
        _cartCreate_body.getRequest().addAll(_cartCreate_bodyRequest);
        com.amazon.webservices.awsecommerceservice.CartCreateResponse _cartCreate__return = port.cartCreate(_cartCreate_body);
        System.out.println("cartCreate.result=" + _cartCreate__return);


        }
        {
        System.out.println("Invoking browseNodeLookup...");
        com.amazon.webservices.awsecommerceservice.BrowseNodeLookup _browseNodeLookup_body = new com.amazon.webservices.awsecommerceservice.BrowseNodeLookup();
        _browseNodeLookup_body.setMarketplaceDomain("MarketplaceDomain1326056350");
        _browseNodeLookup_body.setAWSAccessKeyId("AWSAccessKeyId-754412083");
        _browseNodeLookup_body.setAssociateTag("AssociateTag-1361817303");
        _browseNodeLookup_body.setValidate("Validate-324473079");
        _browseNodeLookup_body.setXMLEscaping("XMLEscaping-1423296173");
        com.amazon.webservices.awsecommerceservice.BrowseNodeLookupRequest _browseNodeLookup_bodyShared = new com.amazon.webservices.awsecommerceservice.BrowseNodeLookupRequest();
        java.util.List<java.lang.String> _browseNodeLookup_bodySharedBrowseNodeId = new java.util.ArrayList<java.lang.String>();
        java.lang.String _browseNodeLookup_bodySharedBrowseNodeIdVal1 = "_browseNodeLookup_bodySharedBrowseNodeIdVal-201799707";
        _browseNodeLookup_bodySharedBrowseNodeId.add(_browseNodeLookup_bodySharedBrowseNodeIdVal1);
        _browseNodeLookup_bodyShared.getBrowseNodeId().addAll(_browseNodeLookup_bodySharedBrowseNodeId);
        java.util.List<java.lang.String> _browseNodeLookup_bodySharedResponseGroup = new java.util.ArrayList<java.lang.String>();
        java.lang.String _browseNodeLookup_bodySharedResponseGroupVal1 = "_browseNodeLookup_bodySharedResponseGroupVal-1039712792";
        _browseNodeLookup_bodySharedResponseGroup.add(_browseNodeLookup_bodySharedResponseGroupVal1);
        _browseNodeLookup_bodyShared.getResponseGroup().addAll(_browseNodeLookup_bodySharedResponseGroup);
        _browseNodeLookup_body.setShared(_browseNodeLookup_bodyShared);
        java.util.List<com.amazon.webservices.awsecommerceservice.BrowseNodeLookupRequest> _browseNodeLookup_bodyRequest = new java.util.ArrayList<com.amazon.webservices.awsecommerceservice.BrowseNodeLookupRequest>();
        com.amazon.webservices.awsecommerceservice.BrowseNodeLookupRequest _browseNodeLookup_bodyRequestVal1 = new com.amazon.webservices.awsecommerceservice.BrowseNodeLookupRequest();
        java.util.List<java.lang.String> _browseNodeLookup_bodyRequestVal1BrowseNodeId = new java.util.ArrayList<java.lang.String>();
        _browseNodeLookup_bodyRequestVal1.getBrowseNodeId().addAll(_browseNodeLookup_bodyRequestVal1BrowseNodeId);
        java.util.List<java.lang.String> _browseNodeLookup_bodyRequestVal1ResponseGroup = new java.util.ArrayList<java.lang.String>();
        _browseNodeLookup_bodyRequestVal1.getResponseGroup().addAll(_browseNodeLookup_bodyRequestVal1ResponseGroup);
        _browseNodeLookup_bodyRequest.add(_browseNodeLookup_bodyRequestVal1);
        _browseNodeLookup_body.getRequest().addAll(_browseNodeLookup_bodyRequest);
        com.amazon.webservices.awsecommerceservice.BrowseNodeLookupResponse _browseNodeLookup__return = port.browseNodeLookup(_browseNodeLookup_body);
        System.out.println("browseNodeLookup.result=" + _browseNodeLookup__return);


        }
        {
        System.out.println("Invoking cartGet...");
        com.amazon.webservices.awsecommerceservice.CartGet _cartGet_body = new com.amazon.webservices.awsecommerceservice.CartGet();
        _cartGet_body.setMarketplaceDomain("MarketplaceDomain1046207364");
        _cartGet_body.setAWSAccessKeyId("AWSAccessKeyId-78327733");
        _cartGet_body.setAssociateTag("AssociateTag-1899969470");
        _cartGet_body.setValidate("Validate-1678054126");
        _cartGet_body.setXMLEscaping("XMLEscaping-810987803");
        com.amazon.webservices.awsecommerceservice.CartGetRequest _cartGet_bodyShared = new com.amazon.webservices.awsecommerceservice.CartGetRequest();
        _cartGet_bodyShared.setCartId("CartId1299206455");
        _cartGet_bodyShared.setHMAC("HMAC-401561227");
        _cartGet_bodyShared.setMergeCart("MergeCart528472261");
        java.util.List<java.lang.String> _cartGet_bodySharedResponseGroup = new java.util.ArrayList<java.lang.String>();
        java.lang.String _cartGet_bodySharedResponseGroupVal1 = "_cartGet_bodySharedResponseGroupVal-800788200";
        _cartGet_bodySharedResponseGroup.add(_cartGet_bodySharedResponseGroupVal1);
        _cartGet_bodyShared.getResponseGroup().addAll(_cartGet_bodySharedResponseGroup);
        _cartGet_body.setShared(_cartGet_bodyShared);
        java.util.List<com.amazon.webservices.awsecommerceservice.CartGetRequest> _cartGet_bodyRequest = new java.util.ArrayList<com.amazon.webservices.awsecommerceservice.CartGetRequest>();
        com.amazon.webservices.awsecommerceservice.CartGetRequest _cartGet_bodyRequestVal1 = new com.amazon.webservices.awsecommerceservice.CartGetRequest();
        _cartGet_bodyRequestVal1.setCartId("CartId-698652059");
        _cartGet_bodyRequestVal1.setHMAC("HMAC1521030311");
        _cartGet_bodyRequestVal1.setMergeCart("MergeCart534640712");
        java.util.List<java.lang.String> _cartGet_bodyRequestVal1ResponseGroup = new java.util.ArrayList<java.lang.String>();
        _cartGet_bodyRequestVal1.getResponseGroup().addAll(_cartGet_bodyRequestVal1ResponseGroup);
        _cartGet_bodyRequest.add(_cartGet_bodyRequestVal1);
        _cartGet_body.getRequest().addAll(_cartGet_bodyRequest);
        com.amazon.webservices.awsecommerceservice.CartGetResponse _cartGet__return = port.cartGet(_cartGet_body);
        System.out.println("cartGet.result=" + _cartGet__return);


        }
        {
        System.out.println("Invoking cartModify...");
        com.amazon.webservices.awsecommerceservice.CartModify _cartModify_body = new com.amazon.webservices.awsecommerceservice.CartModify();
        _cartModify_body.setMarketplaceDomain("MarketplaceDomain275799503");
        _cartModify_body.setAWSAccessKeyId("AWSAccessKeyId-657267153");
        _cartModify_body.setAssociateTag("AssociateTag228673793");
        _cartModify_body.setValidate("Validate206003623");
        _cartModify_body.setXMLEscaping("XMLEscaping-1765067646");
        com.amazon.webservices.awsecommerceservice.CartModifyRequest _cartModify_bodyShared = new com.amazon.webservices.awsecommerceservice.CartModifyRequest();
        _cartModify_bodyShared.setCartId("CartId-1726212940");
        _cartModify_bodyShared.setHMAC("HMAC1490938190");
        _cartModify_bodyShared.setMergeCart("MergeCart-1134651263");
        com.amazon.webservices.awsecommerceservice.CartModifyRequest.Items _cartModify_bodySharedItems = new com.amazon.webservices.awsecommerceservice.CartModifyRequest.Items();
        java.util.List<com.amazon.webservices.awsecommerceservice.CartModifyRequest.Items.Item> _cartModify_bodySharedItemsItem = new java.util.ArrayList<com.amazon.webservices.awsecommerceservice.CartModifyRequest.Items.Item>();
        _cartModify_bodySharedItems.getItem().addAll(_cartModify_bodySharedItemsItem);
        _cartModify_bodyShared.setItems(_cartModify_bodySharedItems);
        java.util.List<java.lang.String> _cartModify_bodySharedResponseGroup = new java.util.ArrayList<java.lang.String>();
        java.lang.String _cartModify_bodySharedResponseGroupVal1 = "_cartModify_bodySharedResponseGroupVal1707451575";
        _cartModify_bodySharedResponseGroup.add(_cartModify_bodySharedResponseGroupVal1);
        _cartModify_bodyShared.getResponseGroup().addAll(_cartModify_bodySharedResponseGroup);
        _cartModify_body.setShared(_cartModify_bodyShared);
        java.util.List<com.amazon.webservices.awsecommerceservice.CartModifyRequest> _cartModify_bodyRequest = new java.util.ArrayList<com.amazon.webservices.awsecommerceservice.CartModifyRequest>();
        com.amazon.webservices.awsecommerceservice.CartModifyRequest _cartModify_bodyRequestVal1 = new com.amazon.webservices.awsecommerceservice.CartModifyRequest();
        _cartModify_bodyRequestVal1.setCartId("CartId-1619026742");
        _cartModify_bodyRequestVal1.setHMAC("HMAC-1543034913");
        _cartModify_bodyRequestVal1.setMergeCart("MergeCart1816130079");
        com.amazon.webservices.awsecommerceservice.CartModifyRequest.Items _cartModify_bodyRequestVal1Items = new com.amazon.webservices.awsecommerceservice.CartModifyRequest.Items();
        java.util.List<com.amazon.webservices.awsecommerceservice.CartModifyRequest.Items.Item> _cartModify_bodyRequestVal1ItemsItem = new java.util.ArrayList<com.amazon.webservices.awsecommerceservice.CartModifyRequest.Items.Item>();
        _cartModify_bodyRequestVal1Items.getItem().addAll(_cartModify_bodyRequestVal1ItemsItem);
        _cartModify_bodyRequestVal1.setItems(_cartModify_bodyRequestVal1Items);
        java.util.List<java.lang.String> _cartModify_bodyRequestVal1ResponseGroup = new java.util.ArrayList<java.lang.String>();
        _cartModify_bodyRequestVal1.getResponseGroup().addAll(_cartModify_bodyRequestVal1ResponseGroup);
        _cartModify_bodyRequest.add(_cartModify_bodyRequestVal1);
        _cartModify_body.getRequest().addAll(_cartModify_bodyRequest);
        com.amazon.webservices.awsecommerceservice.CartModifyResponse _cartModify__return = port.cartModify(_cartModify_body);
        System.out.println("cartModify.result=" + _cartModify__return);


        }
        {
        System.out.println("Invoking cartAdd...");
        com.amazon.webservices.awsecommerceservice.CartAdd _cartAdd_body = new com.amazon.webservices.awsecommerceservice.CartAdd();
        _cartAdd_body.setMarketplaceDomain("MarketplaceDomain-772212093");
        _cartAdd_body.setAWSAccessKeyId("AWSAccessKeyId200009778");
        _cartAdd_body.setAssociateTag("AssociateTag-942174033");
        _cartAdd_body.setValidate("Validate-2049321271");
        _cartAdd_body.setXMLEscaping("XMLEscaping-1663176880");
        com.amazon.webservices.awsecommerceservice.CartAddRequest _cartAdd_bodyShared = new com.amazon.webservices.awsecommerceservice.CartAddRequest();
        _cartAdd_bodyShared.setCartId("CartId785751821");
        _cartAdd_bodyShared.setHMAC("HMAC998953414");
        _cartAdd_bodyShared.setMergeCart("MergeCart-179175340");
        com.amazon.webservices.awsecommerceservice.CartAddRequest.Items _cartAdd_bodySharedItems = new com.amazon.webservices.awsecommerceservice.CartAddRequest.Items();
        java.util.List<com.amazon.webservices.awsecommerceservice.CartAddRequest.Items.Item> _cartAdd_bodySharedItemsItem = new java.util.ArrayList<com.amazon.webservices.awsecommerceservice.CartAddRequest.Items.Item>();
        _cartAdd_bodySharedItems.getItem().addAll(_cartAdd_bodySharedItemsItem);
        _cartAdd_bodyShared.setItems(_cartAdd_bodySharedItems);
        java.util.List<java.lang.String> _cartAdd_bodySharedResponseGroup = new java.util.ArrayList<java.lang.String>();
        java.lang.String _cartAdd_bodySharedResponseGroupVal1 = "_cartAdd_bodySharedResponseGroupVal1620099807";
        _cartAdd_bodySharedResponseGroup.add(_cartAdd_bodySharedResponseGroupVal1);
        _cartAdd_bodyShared.getResponseGroup().addAll(_cartAdd_bodySharedResponseGroup);
        _cartAdd_body.setShared(_cartAdd_bodyShared);
        java.util.List<com.amazon.webservices.awsecommerceservice.CartAddRequest> _cartAdd_bodyRequest = new java.util.ArrayList<com.amazon.webservices.awsecommerceservice.CartAddRequest>();
        com.amazon.webservices.awsecommerceservice.CartAddRequest _cartAdd_bodyRequestVal1 = new com.amazon.webservices.awsecommerceservice.CartAddRequest();
        _cartAdd_bodyRequestVal1.setCartId("CartId568321679");
        _cartAdd_bodyRequestVal1.setHMAC("HMAC583411169");
        _cartAdd_bodyRequestVal1.setMergeCart("MergeCart1811559935");
        com.amazon.webservices.awsecommerceservice.CartAddRequest.Items _cartAdd_bodyRequestVal1Items = new com.amazon.webservices.awsecommerceservice.CartAddRequest.Items();
        java.util.List<com.amazon.webservices.awsecommerceservice.CartAddRequest.Items.Item> _cartAdd_bodyRequestVal1ItemsItem = new java.util.ArrayList<com.amazon.webservices.awsecommerceservice.CartAddRequest.Items.Item>();
        _cartAdd_bodyRequestVal1Items.getItem().addAll(_cartAdd_bodyRequestVal1ItemsItem);
        _cartAdd_bodyRequestVal1.setItems(_cartAdd_bodyRequestVal1Items);
        java.util.List<java.lang.String> _cartAdd_bodyRequestVal1ResponseGroup = new java.util.ArrayList<java.lang.String>();
        _cartAdd_bodyRequestVal1.getResponseGroup().addAll(_cartAdd_bodyRequestVal1ResponseGroup);
        _cartAdd_bodyRequest.add(_cartAdd_bodyRequestVal1);
        _cartAdd_body.getRequest().addAll(_cartAdd_bodyRequest);
        com.amazon.webservices.awsecommerceservice.CartAddResponse _cartAdd__return = port.cartAdd(_cartAdd_body);
        System.out.println("cartAdd.result=" + _cartAdd__return);


        }
        {
        System.out.println("Invoking itemLookup...");
        com.amazon.webservices.awsecommerceservice.ItemLookup _itemLookup_body = new com.amazon.webservices.awsecommerceservice.ItemLookup();
        _itemLookup_body.setMarketplaceDomain("MarketplaceDomain-1513135984");
        _itemLookup_body.setAWSAccessKeyId("AWSAccessKeyId-851618062");
        _itemLookup_body.setAssociateTag("AssociateTag164250962");
        _itemLookup_body.setValidate("Validate707835264");
        _itemLookup_body.setXMLEscaping("XMLEscaping-1386343199");
        com.amazon.webservices.awsecommerceservice.ItemLookupRequest _itemLookup_bodyShared = new com.amazon.webservices.awsecommerceservice.ItemLookupRequest();
        _itemLookup_bodyShared.setCondition("Condition-262808404");
        _itemLookup_bodyShared.setIdType("IdType1348010277");
        _itemLookup_bodyShared.setMerchantId("MerchantId162896216");
        java.util.List<java.lang.String> _itemLookup_bodySharedItemId = new java.util.ArrayList<java.lang.String>();
        java.lang.String _itemLookup_bodySharedItemIdVal1 = "_itemLookup_bodySharedItemIdVal-1111255244";
        _itemLookup_bodySharedItemId.add(_itemLookup_bodySharedItemIdVal1);
        _itemLookup_bodyShared.getItemId().addAll(_itemLookup_bodySharedItemId);
        java.util.List<java.lang.String> _itemLookup_bodySharedResponseGroup = new java.util.ArrayList<java.lang.String>();
        java.lang.String _itemLookup_bodySharedResponseGroupVal1 = "_itemLookup_bodySharedResponseGroupVal609024227";
        _itemLookup_bodySharedResponseGroup.add(_itemLookup_bodySharedResponseGroupVal1);
        _itemLookup_bodyShared.getResponseGroup().addAll(_itemLookup_bodySharedResponseGroup);
        _itemLookup_bodyShared.setSearchIndex("SearchIndex-575214460");
        _itemLookup_bodyShared.setVariationPage("VariationPage-2134912913");
        _itemLookup_bodyShared.setRelatedItemPage("RelatedItemPage-569021484");
        java.util.List<java.lang.String> _itemLookup_bodySharedRelationshipType = new java.util.ArrayList<java.lang.String>();
        java.lang.String _itemLookup_bodySharedRelationshipTypeVal1 = "_itemLookup_bodySharedRelationshipTypeVal-658041568";
        _itemLookup_bodySharedRelationshipType.add(_itemLookup_bodySharedRelationshipTypeVal1);
        _itemLookup_bodyShared.getRelationshipType().addAll(_itemLookup_bodySharedRelationshipType);
        _itemLookup_bodyShared.setIncludeReviewsSummary("IncludeReviewsSummary1272166492");
        _itemLookup_bodyShared.setTruncateReviewsAt(new java.math.BigInteger("-5985621910480562637350963394988090687"));
        _itemLookup_body.setShared(_itemLookup_bodyShared);
        java.util.List<com.amazon.webservices.awsecommerceservice.ItemLookupRequest> _itemLookup_bodyRequest = new java.util.ArrayList<com.amazon.webservices.awsecommerceservice.ItemLookupRequest>();
        com.amazon.webservices.awsecommerceservice.ItemLookupRequest _itemLookup_bodyRequestVal1 = new com.amazon.webservices.awsecommerceservice.ItemLookupRequest();
        _itemLookup_bodyRequestVal1.setCondition("Condition-386613245");
        _itemLookup_bodyRequestVal1.setIdType("IdType-1600834677");
        _itemLookup_bodyRequestVal1.setMerchantId("MerchantId374266550");
        java.util.List<java.lang.String> _itemLookup_bodyRequestVal1ItemId = new java.util.ArrayList<java.lang.String>();
        _itemLookup_bodyRequestVal1.getItemId().addAll(_itemLookup_bodyRequestVal1ItemId);
        java.util.List<java.lang.String> _itemLookup_bodyRequestVal1ResponseGroup = new java.util.ArrayList<java.lang.String>();
        _itemLookup_bodyRequestVal1.getResponseGroup().addAll(_itemLookup_bodyRequestVal1ResponseGroup);
        _itemLookup_bodyRequestVal1.setSearchIndex("SearchIndex-1902989428");
        _itemLookup_bodyRequestVal1.setVariationPage("VariationPage159871460");
        _itemLookup_bodyRequestVal1.setRelatedItemPage("RelatedItemPage-1342108");
        java.util.List<java.lang.String> _itemLookup_bodyRequestVal1RelationshipType = new java.util.ArrayList<java.lang.String>();
        _itemLookup_bodyRequestVal1.getRelationshipType().addAll(_itemLookup_bodyRequestVal1RelationshipType);
        _itemLookup_bodyRequestVal1.setIncludeReviewsSummary("IncludeReviewsSummary-1960398875");
        _itemLookup_bodyRequestVal1.setTruncateReviewsAt(new java.math.BigInteger("7228939084227219890316988266462131475"));
        _itemLookup_bodyRequest.add(_itemLookup_bodyRequestVal1);
        _itemLookup_body.getRequest().addAll(_itemLookup_bodyRequest);
        com.amazon.webservices.awsecommerceservice.ItemLookupResponse _itemLookup__return = port.itemLookup(_itemLookup_body);
        System.out.println("itemLookup.result=" + _itemLookup__return);


        }
        {
        System.out.println("Invoking similarityLookup...");
        com.amazon.webservices.awsecommerceservice.SimilarityLookup _similarityLookup_body = new com.amazon.webservices.awsecommerceservice.SimilarityLookup();
        _similarityLookup_body.setMarketplaceDomain("MarketplaceDomain1650538847");
        _similarityLookup_body.setAWSAccessKeyId("AWSAccessKeyId-1281095261");
        _similarityLookup_body.setAssociateTag("AssociateTag832835004");
        _similarityLookup_body.setValidate("Validate1074159763");
        _similarityLookup_body.setXMLEscaping("XMLEscaping-579163817");
        com.amazon.webservices.awsecommerceservice.SimilarityLookupRequest _similarityLookup_bodyShared = new com.amazon.webservices.awsecommerceservice.SimilarityLookupRequest();
        _similarityLookup_bodyShared.setCondition("Condition1999908870");
        java.util.List<java.lang.String> _similarityLookup_bodySharedItemId = new java.util.ArrayList<java.lang.String>();
        java.lang.String _similarityLookup_bodySharedItemIdVal1 = "_similarityLookup_bodySharedItemIdVal1479987738";
        _similarityLookup_bodySharedItemId.add(_similarityLookup_bodySharedItemIdVal1);
        _similarityLookup_bodyShared.getItemId().addAll(_similarityLookup_bodySharedItemId);
        _similarityLookup_bodyShared.setMerchantId("MerchantId-1730480009");
        java.util.List<java.lang.String> _similarityLookup_bodySharedResponseGroup = new java.util.ArrayList<java.lang.String>();
        java.lang.String _similarityLookup_bodySharedResponseGroupVal1 = "_similarityLookup_bodySharedResponseGroupVal792938403";
        _similarityLookup_bodySharedResponseGroup.add(_similarityLookup_bodySharedResponseGroupVal1);
        _similarityLookup_bodyShared.getResponseGroup().addAll(_similarityLookup_bodySharedResponseGroup);
        _similarityLookup_bodyShared.setSimilarityType("SimilarityType347727769");
        _similarityLookup_body.setShared(_similarityLookup_bodyShared);
        java.util.List<com.amazon.webservices.awsecommerceservice.SimilarityLookupRequest> _similarityLookup_bodyRequest = new java.util.ArrayList<com.amazon.webservices.awsecommerceservice.SimilarityLookupRequest>();
        com.amazon.webservices.awsecommerceservice.SimilarityLookupRequest _similarityLookup_bodyRequestVal1 = new com.amazon.webservices.awsecommerceservice.SimilarityLookupRequest();
        _similarityLookup_bodyRequestVal1.setCondition("Condition-861948406");
        java.util.List<java.lang.String> _similarityLookup_bodyRequestVal1ItemId = new java.util.ArrayList<java.lang.String>();
        _similarityLookup_bodyRequestVal1.getItemId().addAll(_similarityLookup_bodyRequestVal1ItemId);
        _similarityLookup_bodyRequestVal1.setMerchantId("MerchantId-1271138424");
        java.util.List<java.lang.String> _similarityLookup_bodyRequestVal1ResponseGroup = new java.util.ArrayList<java.lang.String>();
        _similarityLookup_bodyRequestVal1.getResponseGroup().addAll(_similarityLookup_bodyRequestVal1ResponseGroup);
        _similarityLookup_bodyRequestVal1.setSimilarityType("SimilarityType1173299311");
        _similarityLookup_bodyRequest.add(_similarityLookup_bodyRequestVal1);
        _similarityLookup_body.getRequest().addAll(_similarityLookup_bodyRequest);
        com.amazon.webservices.awsecommerceservice.SimilarityLookupResponse _similarityLookup__return = port.similarityLookup(_similarityLookup_body);
        System.out.println("similarityLookup.result=" + _similarityLookup__return);


        }
        {
        System.out.println("Invoking itemSearch...");
        com.amazon.webservices.awsecommerceservice.ItemSearch _itemSearch_body = new com.amazon.webservices.awsecommerceservice.ItemSearch();
        _itemSearch_body.setMarketplaceDomain("MarketplaceDomain1727164700");
        _itemSearch_body.setAWSAccessKeyId("AWSAccessKeyId-1851329623");
        _itemSearch_body.setAssociateTag("AssociateTag1977081274");
        _itemSearch_body.setXMLEscaping("XMLEscaping-913003573");
        _itemSearch_body.setValidate("Validate-1023196639");
        com.amazon.webservices.awsecommerceservice.ItemSearchRequest _itemSearch_bodyShared = new com.amazon.webservices.awsecommerceservice.ItemSearchRequest();
        _itemSearch_bodyShared.setActor("Actor1241635680");
        _itemSearch_bodyShared.setArtist("Artist-920442122");
        _itemSearch_bodyShared.setAvailability("Availability922714506");
        java.util.List<java.lang.String> _itemSearch_bodySharedAudienceRating = new java.util.ArrayList<java.lang.String>();
        java.lang.String _itemSearch_bodySharedAudienceRatingVal1 = "_itemSearch_bodySharedAudienceRatingVal1073706278";
        _itemSearch_bodySharedAudienceRating.add(_itemSearch_bodySharedAudienceRatingVal1);
        _itemSearch_bodyShared.getAudienceRating().addAll(_itemSearch_bodySharedAudienceRating);
        _itemSearch_bodyShared.setAuthor("Author960857192");
        _itemSearch_bodyShared.setBrand("Brand1156849490");
        _itemSearch_bodyShared.setBrowseNode("BrowseNode-1080039572");
        _itemSearch_bodyShared.setComposer("Composer-1966364955");
        _itemSearch_bodyShared.setCondition("Condition372605327");
        _itemSearch_bodyShared.setConductor("Conductor169724546");
        _itemSearch_bodyShared.setDirector("Director945986943");
        _itemSearch_bodyShared.setItemPage(new java.math.BigInteger("-70746394407393939896167646100220113727"));
        _itemSearch_bodyShared.setKeywords("Keywords-1057222300");
        _itemSearch_bodyShared.setManufacturer("Manufacturer1355409327");
        _itemSearch_bodyShared.setMaximumPrice(new java.math.BigInteger("8136308816653073418470098667351869069"));
        _itemSearch_bodyShared.setMerchantId("MerchantId-1146790931");
        _itemSearch_bodyShared.setMinimumPrice(new java.math.BigInteger("89951476781387165319123497465286572742"));
        _itemSearch_bodyShared.setMinPercentageOff(new java.math.BigInteger("-71135540345858179614942671138579830358"));
        _itemSearch_bodyShared.setMusicLabel("MusicLabel545055651");
        _itemSearch_bodyShared.setOrchestra("Orchestra-1212890695");
        _itemSearch_bodyShared.setPower("Power1141310322");
        _itemSearch_bodyShared.setPublisher("Publisher-522827635");
        _itemSearch_bodyShared.setRelatedItemPage("RelatedItemPage-1259842233");
        java.util.List<java.lang.String> _itemSearch_bodySharedRelationshipType = new java.util.ArrayList<java.lang.String>();
        java.lang.String _itemSearch_bodySharedRelationshipTypeVal1 = "_itemSearch_bodySharedRelationshipTypeVal1025618800";
        _itemSearch_bodySharedRelationshipType.add(_itemSearch_bodySharedRelationshipTypeVal1);
        _itemSearch_bodyShared.getRelationshipType().addAll(_itemSearch_bodySharedRelationshipType);
        java.util.List<java.lang.String> _itemSearch_bodySharedResponseGroup = new java.util.ArrayList<java.lang.String>();
        java.lang.String _itemSearch_bodySharedResponseGroupVal1 = "_itemSearch_bodySharedResponseGroupVal-959296286";
        _itemSearch_bodySharedResponseGroup.add(_itemSearch_bodySharedResponseGroupVal1);
        _itemSearch_bodyShared.getResponseGroup().addAll(_itemSearch_bodySharedResponseGroup);
        _itemSearch_bodyShared.setSearchIndex("SearchIndex-1852166610");
        _itemSearch_bodyShared.setSort("Sort1173115224");
        _itemSearch_bodyShared.setTitle("Title410471985");
        _itemSearch_bodyShared.setReleaseDate("ReleaseDate-2131396584");
        _itemSearch_bodyShared.setIncludeReviewsSummary("IncludeReviewsSummary785891723");
        _itemSearch_bodyShared.setTruncateReviewsAt(new java.math.BigInteger("59909820124850587856682022655691704681"));
        _itemSearch_body.setShared(_itemSearch_bodyShared);
        java.util.List<com.amazon.webservices.awsecommerceservice.ItemSearchRequest> _itemSearch_bodyRequest = new java.util.ArrayList<com.amazon.webservices.awsecommerceservice.ItemSearchRequest>();
        com.amazon.webservices.awsecommerceservice.ItemSearchRequest _itemSearch_bodyRequestVal1 = new com.amazon.webservices.awsecommerceservice.ItemSearchRequest();
        _itemSearch_bodyRequestVal1.setActor("Actor353522193");
        _itemSearch_bodyRequestVal1.setArtist("Artist308202156");
        _itemSearch_bodyRequestVal1.setAvailability("Availability-1255291982");
        java.util.List<java.lang.String> _itemSearch_bodyRequestVal1AudienceRating = new java.util.ArrayList<java.lang.String>();
        _itemSearch_bodyRequestVal1.getAudienceRating().addAll(_itemSearch_bodyRequestVal1AudienceRating);
        _itemSearch_bodyRequestVal1.setAuthor("Author-138567127");
        _itemSearch_bodyRequestVal1.setBrand("Brand-2058926093");
        _itemSearch_bodyRequestVal1.setBrowseNode("BrowseNode1957982740");
        _itemSearch_bodyRequestVal1.setComposer("Composer1604785152");
        _itemSearch_bodyRequestVal1.setCondition("Condition-1323181768");
        _itemSearch_bodyRequestVal1.setConductor("Conductor286532285");
        _itemSearch_bodyRequestVal1.setDirector("Director1011456332");
        _itemSearch_bodyRequestVal1.setItemPage(new java.math.BigInteger("74318378822270687416644036089577636807"));
        _itemSearch_bodyRequestVal1.setKeywords("Keywords1052259324");
        _itemSearch_bodyRequestVal1.setManufacturer("Manufacturer-105617384");
        _itemSearch_bodyRequestVal1.setMaximumPrice(new java.math.BigInteger("-6572045678026012057211971338430443694"));
        _itemSearch_bodyRequestVal1.setMerchantId("MerchantId514104575");
        _itemSearch_bodyRequestVal1.setMinimumPrice(new java.math.BigInteger("-68195220916740135038960277112752821672"));
        _itemSearch_bodyRequestVal1.setMinPercentageOff(new java.math.BigInteger("-20920405590783587142245084370126290423"));
        _itemSearch_bodyRequestVal1.setMusicLabel("MusicLabel121233539");
        _itemSearch_bodyRequestVal1.setOrchestra("Orchestra-1281778093");
        _itemSearch_bodyRequestVal1.setPower("Power-1219683278");
        _itemSearch_bodyRequestVal1.setPublisher("Publisher1645895511");
        _itemSearch_bodyRequestVal1.setRelatedItemPage("RelatedItemPage-1216641310");
        java.util.List<java.lang.String> _itemSearch_bodyRequestVal1RelationshipType = new java.util.ArrayList<java.lang.String>();
        _itemSearch_bodyRequestVal1.getRelationshipType().addAll(_itemSearch_bodyRequestVal1RelationshipType);
        java.util.List<java.lang.String> _itemSearch_bodyRequestVal1ResponseGroup = new java.util.ArrayList<java.lang.String>();
        _itemSearch_bodyRequestVal1.getResponseGroup().addAll(_itemSearch_bodyRequestVal1ResponseGroup);
        _itemSearch_bodyRequestVal1.setSearchIndex("SearchIndex-881280242");
        _itemSearch_bodyRequestVal1.setSort("Sort-1013461649");
        _itemSearch_bodyRequestVal1.setTitle("Title1983118235");
        _itemSearch_bodyRequestVal1.setReleaseDate("ReleaseDate830023021");
        _itemSearch_bodyRequestVal1.setIncludeReviewsSummary("IncludeReviewsSummary1484447805");
        _itemSearch_bodyRequestVal1.setTruncateReviewsAt(new java.math.BigInteger("-63699299161205838311287419874059599370"));
        _itemSearch_bodyRequest.add(_itemSearch_bodyRequestVal1);
        _itemSearch_body.getRequest().addAll(_itemSearch_bodyRequest);
        com.amazon.webservices.awsecommerceservice.ItemSearchResponse _itemSearch__return = port.itemSearch(_itemSearch_body);
        System.out.println("itemSearch.result=" + _itemSearch__return);


        }
        {
        System.out.println("Invoking cartClear...");
        com.amazon.webservices.awsecommerceservice.CartClear _cartClear_body = new com.amazon.webservices.awsecommerceservice.CartClear();
        _cartClear_body.setMarketplaceDomain("MarketplaceDomain-741526100");
        _cartClear_body.setAWSAccessKeyId("AWSAccessKeyId-1415451148");
        _cartClear_body.setAssociateTag("AssociateTag-1661760620");
        _cartClear_body.setValidate("Validate-1807772150");
        _cartClear_body.setXMLEscaping("XMLEscaping584760363");
        com.amazon.webservices.awsecommerceservice.CartClearRequest _cartClear_bodyShared = new com.amazon.webservices.awsecommerceservice.CartClearRequest();
        _cartClear_bodyShared.setCartId("CartId-2010065743");
        _cartClear_bodyShared.setHMAC("HMAC1061247871");
        _cartClear_bodyShared.setMergeCart("MergeCart133235067");
        java.util.List<java.lang.String> _cartClear_bodySharedResponseGroup = new java.util.ArrayList<java.lang.String>();
        java.lang.String _cartClear_bodySharedResponseGroupVal1 = "_cartClear_bodySharedResponseGroupVal-1464807166";
        _cartClear_bodySharedResponseGroup.add(_cartClear_bodySharedResponseGroupVal1);
        _cartClear_bodyShared.getResponseGroup().addAll(_cartClear_bodySharedResponseGroup);
        _cartClear_body.setShared(_cartClear_bodyShared);
        java.util.List<com.amazon.webservices.awsecommerceservice.CartClearRequest> _cartClear_bodyRequest = new java.util.ArrayList<com.amazon.webservices.awsecommerceservice.CartClearRequest>();
        com.amazon.webservices.awsecommerceservice.CartClearRequest _cartClear_bodyRequestVal1 = new com.amazon.webservices.awsecommerceservice.CartClearRequest();
        _cartClear_bodyRequestVal1.setCartId("CartId1469397305");
        _cartClear_bodyRequestVal1.setHMAC("HMAC872986394");
        _cartClear_bodyRequestVal1.setMergeCart("MergeCart-1227466803");
        java.util.List<java.lang.String> _cartClear_bodyRequestVal1ResponseGroup = new java.util.ArrayList<java.lang.String>();
        _cartClear_bodyRequestVal1.getResponseGroup().addAll(_cartClear_bodyRequestVal1ResponseGroup);
        _cartClear_bodyRequest.add(_cartClear_bodyRequestVal1);
        _cartClear_body.getRequest().addAll(_cartClear_bodyRequest);
        com.amazon.webservices.awsecommerceservice.CartClearResponse _cartClear__return = port.cartClear(_cartClear_body);
        System.out.println("cartClear.result=" + _cartClear__return);


        }

        System.exit(0);
    }

}
