
package com.amazon.webservices.awsecommerceservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.1.16
 * 2018-10-05T17:30:35.158+05:30
 * Generated source version: 3.1.16
 * 
 */
public final class AWSECommerceServicePortType_AWSECommerceServicePortUS_Client {

    private static final QName SERVICE_NAME = new QName("http://webservices.amazon.com/AWSECommerceService/2011-08-01", "AWSECommerceService");

    private AWSECommerceServicePortType_AWSECommerceServicePortUS_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = AWSECommerceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        AWSECommerceService ss = new AWSECommerceService(wsdlURL, SERVICE_NAME);
        AWSECommerceServicePortType port = ss.getAWSECommerceServicePortUS();  
        
        {
        System.out.println("Invoking cartCreate...");
        com.amazon.webservices.awsecommerceservice.CartCreate _cartCreate_body = new com.amazon.webservices.awsecommerceservice.CartCreate();
        _cartCreate_body.setMarketplaceDomain("MarketplaceDomain-3893727");
        _cartCreate_body.setAWSAccessKeyId("AWSAccessKeyId-57849104");
        _cartCreate_body.setAssociateTag("AssociateTag1906589497");
        _cartCreate_body.setValidate("Validate1056921853");
        _cartCreate_body.setXMLEscaping("XMLEscaping1347772686");
        com.amazon.webservices.awsecommerceservice.CartCreateRequest _cartCreate_bodyShared = new com.amazon.webservices.awsecommerceservice.CartCreateRequest();
        _cartCreate_bodyShared.setMergeCart("MergeCart-1283158110");
        com.amazon.webservices.awsecommerceservice.CartCreateRequest.Items _cartCreate_bodySharedItems = new com.amazon.webservices.awsecommerceservice.CartCreateRequest.Items();
        java.util.List<com.amazon.webservices.awsecommerceservice.CartCreateRequest.Items.Item> _cartCreate_bodySharedItemsItem = new java.util.ArrayList<com.amazon.webservices.awsecommerceservice.CartCreateRequest.Items.Item>();
        _cartCreate_bodySharedItems.getItem().addAll(_cartCreate_bodySharedItemsItem);
        _cartCreate_bodyShared.setItems(_cartCreate_bodySharedItems);
        java.util.List<java.lang.String> _cartCreate_bodySharedResponseGroup = new java.util.ArrayList<java.lang.String>();
        java.lang.String _cartCreate_bodySharedResponseGroupVal1 = "_cartCreate_bodySharedResponseGroupVal1988830183";
        _cartCreate_bodySharedResponseGroup.add(_cartCreate_bodySharedResponseGroupVal1);
        _cartCreate_bodyShared.getResponseGroup().addAll(_cartCreate_bodySharedResponseGroup);
        _cartCreate_body.setShared(_cartCreate_bodyShared);
        java.util.List<com.amazon.webservices.awsecommerceservice.CartCreateRequest> _cartCreate_bodyRequest = new java.util.ArrayList<com.amazon.webservices.awsecommerceservice.CartCreateRequest>();
        com.amazon.webservices.awsecommerceservice.CartCreateRequest _cartCreate_bodyRequestVal1 = new com.amazon.webservices.awsecommerceservice.CartCreateRequest();
        _cartCreate_bodyRequestVal1.setMergeCart("MergeCart-289783813");
        com.amazon.webservices.awsecommerceservice.CartCreateRequest.Items _cartCreate_bodyRequestVal1Items = new com.amazon.webservices.awsecommerceservice.CartCreateRequest.Items();
        java.util.List<com.amazon.webservices.awsecommerceservice.CartCreateRequest.Items.Item> _cartCreate_bodyRequestVal1ItemsItem = new java.util.ArrayList<com.amazon.webservices.awsecommerceservice.CartCreateRequest.Items.Item>();
        _cartCreate_bodyRequestVal1Items.getItem().addAll(_cartCreate_bodyRequestVal1ItemsItem);
        _cartCreate_bodyRequestVal1.setItems(_cartCreate_bodyRequestVal1Items);
        java.util.List<java.lang.String> _cartCreate_bodyRequestVal1ResponseGroup = new java.util.ArrayList<java.lang.String>();
        _cartCreate_bodyRequestVal1.getResponseGroup().addAll(_cartCreate_bodyRequestVal1ResponseGroup);
        _cartCreate_bodyRequest.add(_cartCreate_bodyRequestVal1);
        _cartCreate_body.getRequest().addAll(_cartCreate_bodyRequest);
        com.amazon.webservices.awsecommerceservice.CartCreateResponse _cartCreate__return = port.cartCreate(_cartCreate_body);
        System.out.println("cartCreate.result=" + _cartCreate__return);


        }
        {
        System.out.println("Invoking browseNodeLookup...");
        com.amazon.webservices.awsecommerceservice.BrowseNodeLookup _browseNodeLookup_body = new com.amazon.webservices.awsecommerceservice.BrowseNodeLookup();
        _browseNodeLookup_body.setMarketplaceDomain("MarketplaceDomain-19067149");
        _browseNodeLookup_body.setAWSAccessKeyId("AWSAccessKeyId-1596245746");
        _browseNodeLookup_body.setAssociateTag("AssociateTag-1881273341");
        _browseNodeLookup_body.setValidate("Validate2061211374");
        _browseNodeLookup_body.setXMLEscaping("XMLEscaping1105094707");
        com.amazon.webservices.awsecommerceservice.BrowseNodeLookupRequest _browseNodeLookup_bodyShared = new com.amazon.webservices.awsecommerceservice.BrowseNodeLookupRequest();
        java.util.List<java.lang.String> _browseNodeLookup_bodySharedBrowseNodeId = new java.util.ArrayList<java.lang.String>();
        java.lang.String _browseNodeLookup_bodySharedBrowseNodeIdVal1 = "_browseNodeLookup_bodySharedBrowseNodeIdVal-643564200";
        _browseNodeLookup_bodySharedBrowseNodeId.add(_browseNodeLookup_bodySharedBrowseNodeIdVal1);
        _browseNodeLookup_bodyShared.getBrowseNodeId().addAll(_browseNodeLookup_bodySharedBrowseNodeId);
        java.util.List<java.lang.String> _browseNodeLookup_bodySharedResponseGroup = new java.util.ArrayList<java.lang.String>();
        java.lang.String _browseNodeLookup_bodySharedResponseGroupVal1 = "_browseNodeLookup_bodySharedResponseGroupVal328237174";
        _browseNodeLookup_bodySharedResponseGroup.add(_browseNodeLookup_bodySharedResponseGroupVal1);
        _browseNodeLookup_bodyShared.getResponseGroup().addAll(_browseNodeLookup_bodySharedResponseGroup);
        _browseNodeLookup_body.setShared(_browseNodeLookup_bodyShared);
        java.util.List<com.amazon.webservices.awsecommerceservice.BrowseNodeLookupRequest> _browseNodeLookup_bodyRequest = new java.util.ArrayList<com.amazon.webservices.awsecommerceservice.BrowseNodeLookupRequest>();
        com.amazon.webservices.awsecommerceservice.BrowseNodeLookupRequest _browseNodeLookup_bodyRequestVal1 = new com.amazon.webservices.awsecommerceservice.BrowseNodeLookupRequest();
        java.util.List<java.lang.String> _browseNodeLookup_bodyRequestVal1BrowseNodeId = new java.util.ArrayList<java.lang.String>();
        _browseNodeLookup_bodyRequestVal1.getBrowseNodeId().addAll(_browseNodeLookup_bodyRequestVal1BrowseNodeId);
        java.util.List<java.lang.String> _browseNodeLookup_bodyRequestVal1ResponseGroup = new java.util.ArrayList<java.lang.String>();
        _browseNodeLookup_bodyRequestVal1.getResponseGroup().addAll(_browseNodeLookup_bodyRequestVal1ResponseGroup);
        _browseNodeLookup_bodyRequest.add(_browseNodeLookup_bodyRequestVal1);
        _browseNodeLookup_body.getRequest().addAll(_browseNodeLookup_bodyRequest);
        com.amazon.webservices.awsecommerceservice.BrowseNodeLookupResponse _browseNodeLookup__return = port.browseNodeLookup(_browseNodeLookup_body);
        System.out.println("browseNodeLookup.result=" + _browseNodeLookup__return);


        }
        {
        System.out.println("Invoking cartGet...");
        com.amazon.webservices.awsecommerceservice.CartGet _cartGet_body = new com.amazon.webservices.awsecommerceservice.CartGet();
        _cartGet_body.setMarketplaceDomain("MarketplaceDomain-222104509");
        _cartGet_body.setAWSAccessKeyId("AWSAccessKeyId-247647133");
        _cartGet_body.setAssociateTag("AssociateTag1128613622");
        _cartGet_body.setValidate("Validate244233904");
        _cartGet_body.setXMLEscaping("XMLEscaping-1861739871");
        com.amazon.webservices.awsecommerceservice.CartGetRequest _cartGet_bodyShared = new com.amazon.webservices.awsecommerceservice.CartGetRequest();
        _cartGet_bodyShared.setCartId("CartId177287745");
        _cartGet_bodyShared.setHMAC("HMAC-1568538733");
        _cartGet_bodyShared.setMergeCart("MergeCart1408551864");
        java.util.List<java.lang.String> _cartGet_bodySharedResponseGroup = new java.util.ArrayList<java.lang.String>();
        java.lang.String _cartGet_bodySharedResponseGroupVal1 = "_cartGet_bodySharedResponseGroupVal-1551689614";
        _cartGet_bodySharedResponseGroup.add(_cartGet_bodySharedResponseGroupVal1);
        _cartGet_bodyShared.getResponseGroup().addAll(_cartGet_bodySharedResponseGroup);
        _cartGet_body.setShared(_cartGet_bodyShared);
        java.util.List<com.amazon.webservices.awsecommerceservice.CartGetRequest> _cartGet_bodyRequest = new java.util.ArrayList<com.amazon.webservices.awsecommerceservice.CartGetRequest>();
        com.amazon.webservices.awsecommerceservice.CartGetRequest _cartGet_bodyRequestVal1 = new com.amazon.webservices.awsecommerceservice.CartGetRequest();
        _cartGet_bodyRequestVal1.setCartId("CartId1318853348");
        _cartGet_bodyRequestVal1.setHMAC("HMAC-1182161611");
        _cartGet_bodyRequestVal1.setMergeCart("MergeCart1914051716");
        java.util.List<java.lang.String> _cartGet_bodyRequestVal1ResponseGroup = new java.util.ArrayList<java.lang.String>();
        _cartGet_bodyRequestVal1.getResponseGroup().addAll(_cartGet_bodyRequestVal1ResponseGroup);
        _cartGet_bodyRequest.add(_cartGet_bodyRequestVal1);
        _cartGet_body.getRequest().addAll(_cartGet_bodyRequest);
        com.amazon.webservices.awsecommerceservice.CartGetResponse _cartGet__return = port.cartGet(_cartGet_body);
        System.out.println("cartGet.result=" + _cartGet__return);


        }
        {
        System.out.println("Invoking cartModify...");
        com.amazon.webservices.awsecommerceservice.CartModify _cartModify_body = new com.amazon.webservices.awsecommerceservice.CartModify();
        _cartModify_body.setMarketplaceDomain("MarketplaceDomain-1103602782");
        _cartModify_body.setAWSAccessKeyId("AWSAccessKeyId977282101");
        _cartModify_body.setAssociateTag("AssociateTag-1659761247");
        _cartModify_body.setValidate("Validate-332312694");
        _cartModify_body.setXMLEscaping("XMLEscaping973847975");
        com.amazon.webservices.awsecommerceservice.CartModifyRequest _cartModify_bodyShared = new com.amazon.webservices.awsecommerceservice.CartModifyRequest();
        _cartModify_bodyShared.setCartId("CartId1631041181");
        _cartModify_bodyShared.setHMAC("HMAC-71336963");
        _cartModify_bodyShared.setMergeCart("MergeCart1348658070");
        com.amazon.webservices.awsecommerceservice.CartModifyRequest.Items _cartModify_bodySharedItems = new com.amazon.webservices.awsecommerceservice.CartModifyRequest.Items();
        java.util.List<com.amazon.webservices.awsecommerceservice.CartModifyRequest.Items.Item> _cartModify_bodySharedItemsItem = new java.util.ArrayList<com.amazon.webservices.awsecommerceservice.CartModifyRequest.Items.Item>();
        _cartModify_bodySharedItems.getItem().addAll(_cartModify_bodySharedItemsItem);
        _cartModify_bodyShared.setItems(_cartModify_bodySharedItems);
        java.util.List<java.lang.String> _cartModify_bodySharedResponseGroup = new java.util.ArrayList<java.lang.String>();
        java.lang.String _cartModify_bodySharedResponseGroupVal1 = "_cartModify_bodySharedResponseGroupVal-53883968";
        _cartModify_bodySharedResponseGroup.add(_cartModify_bodySharedResponseGroupVal1);
        _cartModify_bodyShared.getResponseGroup().addAll(_cartModify_bodySharedResponseGroup);
        _cartModify_body.setShared(_cartModify_bodyShared);
        java.util.List<com.amazon.webservices.awsecommerceservice.CartModifyRequest> _cartModify_bodyRequest = new java.util.ArrayList<com.amazon.webservices.awsecommerceservice.CartModifyRequest>();
        com.amazon.webservices.awsecommerceservice.CartModifyRequest _cartModify_bodyRequestVal1 = new com.amazon.webservices.awsecommerceservice.CartModifyRequest();
        _cartModify_bodyRequestVal1.setCartId("CartId-2019145217");
        _cartModify_bodyRequestVal1.setHMAC("HMAC1883630775");
        _cartModify_bodyRequestVal1.setMergeCart("MergeCart-936290338");
        com.amazon.webservices.awsecommerceservice.CartModifyRequest.Items _cartModify_bodyRequestVal1Items = new com.amazon.webservices.awsecommerceservice.CartModifyRequest.Items();
        java.util.List<com.amazon.webservices.awsecommerceservice.CartModifyRequest.Items.Item> _cartModify_bodyRequestVal1ItemsItem = new java.util.ArrayList<com.amazon.webservices.awsecommerceservice.CartModifyRequest.Items.Item>();
        _cartModify_bodyRequestVal1Items.getItem().addAll(_cartModify_bodyRequestVal1ItemsItem);
        _cartModify_bodyRequestVal1.setItems(_cartModify_bodyRequestVal1Items);
        java.util.List<java.lang.String> _cartModify_bodyRequestVal1ResponseGroup = new java.util.ArrayList<java.lang.String>();
        _cartModify_bodyRequestVal1.getResponseGroup().addAll(_cartModify_bodyRequestVal1ResponseGroup);
        _cartModify_bodyRequest.add(_cartModify_bodyRequestVal1);
        _cartModify_body.getRequest().addAll(_cartModify_bodyRequest);
        com.amazon.webservices.awsecommerceservice.CartModifyResponse _cartModify__return = port.cartModify(_cartModify_body);
        System.out.println("cartModify.result=" + _cartModify__return);


        }
        {
        System.out.println("Invoking cartAdd...");
        com.amazon.webservices.awsecommerceservice.CartAdd _cartAdd_body = new com.amazon.webservices.awsecommerceservice.CartAdd();
        _cartAdd_body.setMarketplaceDomain("MarketplaceDomain994496384");
        _cartAdd_body.setAWSAccessKeyId("AWSAccessKeyId2091228648");
        _cartAdd_body.setAssociateTag("AssociateTag1475918758");
        _cartAdd_body.setValidate("Validate-466927277");
        _cartAdd_body.setXMLEscaping("XMLEscaping-1270391923");
        com.amazon.webservices.awsecommerceservice.CartAddRequest _cartAdd_bodyShared = new com.amazon.webservices.awsecommerceservice.CartAddRequest();
        _cartAdd_bodyShared.setCartId("CartId-630079227");
        _cartAdd_bodyShared.setHMAC("HMAC-1423177618");
        _cartAdd_bodyShared.setMergeCart("MergeCart-2118065863");
        com.amazon.webservices.awsecommerceservice.CartAddRequest.Items _cartAdd_bodySharedItems = new com.amazon.webservices.awsecommerceservice.CartAddRequest.Items();
        java.util.List<com.amazon.webservices.awsecommerceservice.CartAddRequest.Items.Item> _cartAdd_bodySharedItemsItem = new java.util.ArrayList<com.amazon.webservices.awsecommerceservice.CartAddRequest.Items.Item>();
        _cartAdd_bodySharedItems.getItem().addAll(_cartAdd_bodySharedItemsItem);
        _cartAdd_bodyShared.setItems(_cartAdd_bodySharedItems);
        java.util.List<java.lang.String> _cartAdd_bodySharedResponseGroup = new java.util.ArrayList<java.lang.String>();
        java.lang.String _cartAdd_bodySharedResponseGroupVal1 = "_cartAdd_bodySharedResponseGroupVal870211749";
        _cartAdd_bodySharedResponseGroup.add(_cartAdd_bodySharedResponseGroupVal1);
        _cartAdd_bodyShared.getResponseGroup().addAll(_cartAdd_bodySharedResponseGroup);
        _cartAdd_body.setShared(_cartAdd_bodyShared);
        java.util.List<com.amazon.webservices.awsecommerceservice.CartAddRequest> _cartAdd_bodyRequest = new java.util.ArrayList<com.amazon.webservices.awsecommerceservice.CartAddRequest>();
        com.amazon.webservices.awsecommerceservice.CartAddRequest _cartAdd_bodyRequestVal1 = new com.amazon.webservices.awsecommerceservice.CartAddRequest();
        _cartAdd_bodyRequestVal1.setCartId("CartId1409915861");
        _cartAdd_bodyRequestVal1.setHMAC("HMAC1025342759");
        _cartAdd_bodyRequestVal1.setMergeCart("MergeCart2064126201");
        com.amazon.webservices.awsecommerceservice.CartAddRequest.Items _cartAdd_bodyRequestVal1Items = new com.amazon.webservices.awsecommerceservice.CartAddRequest.Items();
        java.util.List<com.amazon.webservices.awsecommerceservice.CartAddRequest.Items.Item> _cartAdd_bodyRequestVal1ItemsItem = new java.util.ArrayList<com.amazon.webservices.awsecommerceservice.CartAddRequest.Items.Item>();
        _cartAdd_bodyRequestVal1Items.getItem().addAll(_cartAdd_bodyRequestVal1ItemsItem);
        _cartAdd_bodyRequestVal1.setItems(_cartAdd_bodyRequestVal1Items);
        java.util.List<java.lang.String> _cartAdd_bodyRequestVal1ResponseGroup = new java.util.ArrayList<java.lang.String>();
        _cartAdd_bodyRequestVal1.getResponseGroup().addAll(_cartAdd_bodyRequestVal1ResponseGroup);
        _cartAdd_bodyRequest.add(_cartAdd_bodyRequestVal1);
        _cartAdd_body.getRequest().addAll(_cartAdd_bodyRequest);
        com.amazon.webservices.awsecommerceservice.CartAddResponse _cartAdd__return = port.cartAdd(_cartAdd_body);
        System.out.println("cartAdd.result=" + _cartAdd__return);


        }
        {
        System.out.println("Invoking itemLookup...");
        com.amazon.webservices.awsecommerceservice.ItemLookup _itemLookup_body = new com.amazon.webservices.awsecommerceservice.ItemLookup();
        _itemLookup_body.setMarketplaceDomain("MarketplaceDomain-1356263710");
        _itemLookup_body.setAWSAccessKeyId("AWSAccessKeyId-213847394");
        _itemLookup_body.setAssociateTag("AssociateTag-1135584448");
        _itemLookup_body.setValidate("Validate464688949");
        _itemLookup_body.setXMLEscaping("XMLEscaping672204606");
        com.amazon.webservices.awsecommerceservice.ItemLookupRequest _itemLookup_bodyShared = new com.amazon.webservices.awsecommerceservice.ItemLookupRequest();
        _itemLookup_bodyShared.setCondition("Condition-1466166620");
        _itemLookup_bodyShared.setIdType("IdType346223265");
        _itemLookup_bodyShared.setMerchantId("MerchantId980171293");
        java.util.List<java.lang.String> _itemLookup_bodySharedItemId = new java.util.ArrayList<java.lang.String>();
        java.lang.String _itemLookup_bodySharedItemIdVal1 = "_itemLookup_bodySharedItemIdVal-1136549544";
        _itemLookup_bodySharedItemId.add(_itemLookup_bodySharedItemIdVal1);
        _itemLookup_bodyShared.getItemId().addAll(_itemLookup_bodySharedItemId);
        java.util.List<java.lang.String> _itemLookup_bodySharedResponseGroup = new java.util.ArrayList<java.lang.String>();
        java.lang.String _itemLookup_bodySharedResponseGroupVal1 = "_itemLookup_bodySharedResponseGroupVal1327275672";
        _itemLookup_bodySharedResponseGroup.add(_itemLookup_bodySharedResponseGroupVal1);
        _itemLookup_bodyShared.getResponseGroup().addAll(_itemLookup_bodySharedResponseGroup);
        _itemLookup_bodyShared.setSearchIndex("SearchIndex539092751");
        _itemLookup_bodyShared.setVariationPage("VariationPage56042240");
        _itemLookup_bodyShared.setRelatedItemPage("RelatedItemPage-1039840905");
        java.util.List<java.lang.String> _itemLookup_bodySharedRelationshipType = new java.util.ArrayList<java.lang.String>();
        java.lang.String _itemLookup_bodySharedRelationshipTypeVal1 = "_itemLookup_bodySharedRelationshipTypeVal-55955889";
        _itemLookup_bodySharedRelationshipType.add(_itemLookup_bodySharedRelationshipTypeVal1);
        _itemLookup_bodyShared.getRelationshipType().addAll(_itemLookup_bodySharedRelationshipType);
        _itemLookup_bodyShared.setIncludeReviewsSummary("IncludeReviewsSummary889186261");
        _itemLookup_bodyShared.setTruncateReviewsAt(new java.math.BigInteger("89853576188859665435420281933225442719"));
        _itemLookup_body.setShared(_itemLookup_bodyShared);
        java.util.List<com.amazon.webservices.awsecommerceservice.ItemLookupRequest> _itemLookup_bodyRequest = new java.util.ArrayList<com.amazon.webservices.awsecommerceservice.ItemLookupRequest>();
        com.amazon.webservices.awsecommerceservice.ItemLookupRequest _itemLookup_bodyRequestVal1 = new com.amazon.webservices.awsecommerceservice.ItemLookupRequest();
        _itemLookup_bodyRequestVal1.setCondition("Condition857721308");
        _itemLookup_bodyRequestVal1.setIdType("IdType1231952387");
        _itemLookup_bodyRequestVal1.setMerchantId("MerchantId-1837504770");
        java.util.List<java.lang.String> _itemLookup_bodyRequestVal1ItemId = new java.util.ArrayList<java.lang.String>();
        _itemLookup_bodyRequestVal1.getItemId().addAll(_itemLookup_bodyRequestVal1ItemId);
        java.util.List<java.lang.String> _itemLookup_bodyRequestVal1ResponseGroup = new java.util.ArrayList<java.lang.String>();
        _itemLookup_bodyRequestVal1.getResponseGroup().addAll(_itemLookup_bodyRequestVal1ResponseGroup);
        _itemLookup_bodyRequestVal1.setSearchIndex("SearchIndex-1862217048");
        _itemLookup_bodyRequestVal1.setVariationPage("VariationPage884673487");
        _itemLookup_bodyRequestVal1.setRelatedItemPage("RelatedItemPage-1437846549");
        java.util.List<java.lang.String> _itemLookup_bodyRequestVal1RelationshipType = new java.util.ArrayList<java.lang.String>();
        _itemLookup_bodyRequestVal1.getRelationshipType().addAll(_itemLookup_bodyRequestVal1RelationshipType);
        _itemLookup_bodyRequestVal1.setIncludeReviewsSummary("IncludeReviewsSummary-1660550108");
        _itemLookup_bodyRequestVal1.setTruncateReviewsAt(new java.math.BigInteger("-25376100656491817954004373613049009040"));
        _itemLookup_bodyRequest.add(_itemLookup_bodyRequestVal1);
        _itemLookup_body.getRequest().addAll(_itemLookup_bodyRequest);
        com.amazon.webservices.awsecommerceservice.ItemLookupResponse _itemLookup__return = port.itemLookup(_itemLookup_body);
        System.out.println("itemLookup.result=" + _itemLookup__return);


        }
        {
        System.out.println("Invoking similarityLookup...");
        com.amazon.webservices.awsecommerceservice.SimilarityLookup _similarityLookup_body = new com.amazon.webservices.awsecommerceservice.SimilarityLookup();
        _similarityLookup_body.setMarketplaceDomain("MarketplaceDomain1784509350");
        _similarityLookup_body.setAWSAccessKeyId("AWSAccessKeyId1540668329");
        _similarityLookup_body.setAssociateTag("AssociateTag-1766790510");
        _similarityLookup_body.setValidate("Validate-371282925");
        _similarityLookup_body.setXMLEscaping("XMLEscaping195298437");
        com.amazon.webservices.awsecommerceservice.SimilarityLookupRequest _similarityLookup_bodyShared = new com.amazon.webservices.awsecommerceservice.SimilarityLookupRequest();
        _similarityLookup_bodyShared.setCondition("Condition1486123310");
        java.util.List<java.lang.String> _similarityLookup_bodySharedItemId = new java.util.ArrayList<java.lang.String>();
        java.lang.String _similarityLookup_bodySharedItemIdVal1 = "_similarityLookup_bodySharedItemIdVal-888558998";
        _similarityLookup_bodySharedItemId.add(_similarityLookup_bodySharedItemIdVal1);
        _similarityLookup_bodyShared.getItemId().addAll(_similarityLookup_bodySharedItemId);
        _similarityLookup_bodyShared.setMerchantId("MerchantId-1720398823");
        java.util.List<java.lang.String> _similarityLookup_bodySharedResponseGroup = new java.util.ArrayList<java.lang.String>();
        java.lang.String _similarityLookup_bodySharedResponseGroupVal1 = "_similarityLookup_bodySharedResponseGroupVal-130939267";
        _similarityLookup_bodySharedResponseGroup.add(_similarityLookup_bodySharedResponseGroupVal1);
        _similarityLookup_bodyShared.getResponseGroup().addAll(_similarityLookup_bodySharedResponseGroup);
        _similarityLookup_bodyShared.setSimilarityType("SimilarityType1793642646");
        _similarityLookup_body.setShared(_similarityLookup_bodyShared);
        java.util.List<com.amazon.webservices.awsecommerceservice.SimilarityLookupRequest> _similarityLookup_bodyRequest = new java.util.ArrayList<com.amazon.webservices.awsecommerceservice.SimilarityLookupRequest>();
        com.amazon.webservices.awsecommerceservice.SimilarityLookupRequest _similarityLookup_bodyRequestVal1 = new com.amazon.webservices.awsecommerceservice.SimilarityLookupRequest();
        _similarityLookup_bodyRequestVal1.setCondition("Condition661628527");
        java.util.List<java.lang.String> _similarityLookup_bodyRequestVal1ItemId = new java.util.ArrayList<java.lang.String>();
        _similarityLookup_bodyRequestVal1.getItemId().addAll(_similarityLookup_bodyRequestVal1ItemId);
        _similarityLookup_bodyRequestVal1.setMerchantId("MerchantId-1462276067");
        java.util.List<java.lang.String> _similarityLookup_bodyRequestVal1ResponseGroup = new java.util.ArrayList<java.lang.String>();
        _similarityLookup_bodyRequestVal1.getResponseGroup().addAll(_similarityLookup_bodyRequestVal1ResponseGroup);
        _similarityLookup_bodyRequestVal1.setSimilarityType("SimilarityType-1899752361");
        _similarityLookup_bodyRequest.add(_similarityLookup_bodyRequestVal1);
        _similarityLookup_body.getRequest().addAll(_similarityLookup_bodyRequest);
        com.amazon.webservices.awsecommerceservice.SimilarityLookupResponse _similarityLookup__return = port.similarityLookup(_similarityLookup_body);
        System.out.println("similarityLookup.result=" + _similarityLookup__return);


        }
        {
        System.out.println("Invoking itemSearch...");
        com.amazon.webservices.awsecommerceservice.ItemSearch _itemSearch_body = new com.amazon.webservices.awsecommerceservice.ItemSearch();
        _itemSearch_body.setMarketplaceDomain("MarketplaceDomain-945554676");
        _itemSearch_body.setAWSAccessKeyId("AWSAccessKeyId1455402683");
        _itemSearch_body.setAssociateTag("AssociateTag-678863778");
        _itemSearch_body.setXMLEscaping("XMLEscaping-1539440003");
        _itemSearch_body.setValidate("Validate1160143183");
        com.amazon.webservices.awsecommerceservice.ItemSearchRequest _itemSearch_bodyShared = new com.amazon.webservices.awsecommerceservice.ItemSearchRequest();
        _itemSearch_bodyShared.setActor("Actor-1274704526");
        _itemSearch_bodyShared.setArtist("Artist-2139107886");
        _itemSearch_bodyShared.setAvailability("Availability-2010861854");
        java.util.List<java.lang.String> _itemSearch_bodySharedAudienceRating = new java.util.ArrayList<java.lang.String>();
        java.lang.String _itemSearch_bodySharedAudienceRatingVal1 = "_itemSearch_bodySharedAudienceRatingVal305340361";
        _itemSearch_bodySharedAudienceRating.add(_itemSearch_bodySharedAudienceRatingVal1);
        _itemSearch_bodyShared.getAudienceRating().addAll(_itemSearch_bodySharedAudienceRating);
        _itemSearch_bodyShared.setAuthor("Author672215883");
        _itemSearch_bodyShared.setBrand("Brand2052392539");
        _itemSearch_bodyShared.setBrowseNode("BrowseNode1007315743");
        _itemSearch_bodyShared.setComposer("Composer-945453088");
        _itemSearch_bodyShared.setCondition("Condition1049864270");
        _itemSearch_bodyShared.setConductor("Conductor26929208");
        _itemSearch_bodyShared.setDirector("Director1465214174");
        _itemSearch_bodyShared.setItemPage(new java.math.BigInteger("-73573572719450672977784660259265990533"));
        _itemSearch_bodyShared.setKeywords("Keywords1723660327");
        _itemSearch_bodyShared.setManufacturer("Manufacturer344389370");
        _itemSearch_bodyShared.setMaximumPrice(new java.math.BigInteger("-640845654641944089219631339095889855"));
        _itemSearch_bodyShared.setMerchantId("MerchantId-1841250967");
        _itemSearch_bodyShared.setMinimumPrice(new java.math.BigInteger("-11880708990354129046881101316256123242"));
        _itemSearch_bodyShared.setMinPercentageOff(new java.math.BigInteger("1296862874603920852032684489860623373"));
        _itemSearch_bodyShared.setMusicLabel("MusicLabel-1382292480");
        _itemSearch_bodyShared.setOrchestra("Orchestra87702907");
        _itemSearch_bodyShared.setPower("Power-1977487630");
        _itemSearch_bodyShared.setPublisher("Publisher-431181820");
        _itemSearch_bodyShared.setRelatedItemPage("RelatedItemPage1244025095");
        java.util.List<java.lang.String> _itemSearch_bodySharedRelationshipType = new java.util.ArrayList<java.lang.String>();
        java.lang.String _itemSearch_bodySharedRelationshipTypeVal1 = "_itemSearch_bodySharedRelationshipTypeVal324604814";
        _itemSearch_bodySharedRelationshipType.add(_itemSearch_bodySharedRelationshipTypeVal1);
        _itemSearch_bodyShared.getRelationshipType().addAll(_itemSearch_bodySharedRelationshipType);
        java.util.List<java.lang.String> _itemSearch_bodySharedResponseGroup = new java.util.ArrayList<java.lang.String>();
        java.lang.String _itemSearch_bodySharedResponseGroupVal1 = "_itemSearch_bodySharedResponseGroupVal206484256";
        _itemSearch_bodySharedResponseGroup.add(_itemSearch_bodySharedResponseGroupVal1);
        _itemSearch_bodyShared.getResponseGroup().addAll(_itemSearch_bodySharedResponseGroup);
        _itemSearch_bodyShared.setSearchIndex("SearchIndex-1426371544");
        _itemSearch_bodyShared.setSort("Sort-544238063");
        _itemSearch_bodyShared.setTitle("Title764487149");
        _itemSearch_bodyShared.setReleaseDate("ReleaseDate1624835328");
        _itemSearch_bodyShared.setIncludeReviewsSummary("IncludeReviewsSummary601397225");
        _itemSearch_bodyShared.setTruncateReviewsAt(new java.math.BigInteger("-3874444938060685031837105506509173628"));
        _itemSearch_body.setShared(_itemSearch_bodyShared);
        java.util.List<com.amazon.webservices.awsecommerceservice.ItemSearchRequest> _itemSearch_bodyRequest = new java.util.ArrayList<com.amazon.webservices.awsecommerceservice.ItemSearchRequest>();
        com.amazon.webservices.awsecommerceservice.ItemSearchRequest _itemSearch_bodyRequestVal1 = new com.amazon.webservices.awsecommerceservice.ItemSearchRequest();
        _itemSearch_bodyRequestVal1.setActor("Actor847928749");
        _itemSearch_bodyRequestVal1.setArtist("Artist2014174171");
        _itemSearch_bodyRequestVal1.setAvailability("Availability580436322");
        java.util.List<java.lang.String> _itemSearch_bodyRequestVal1AudienceRating = new java.util.ArrayList<java.lang.String>();
        _itemSearch_bodyRequestVal1.getAudienceRating().addAll(_itemSearch_bodyRequestVal1AudienceRating);
        _itemSearch_bodyRequestVal1.setAuthor("Author-1603629856");
        _itemSearch_bodyRequestVal1.setBrand("Brand1006411249");
        _itemSearch_bodyRequestVal1.setBrowseNode("BrowseNode1560945713");
        _itemSearch_bodyRequestVal1.setComposer("Composer1821894918");
        _itemSearch_bodyRequestVal1.setCondition("Condition-1785163588");
        _itemSearch_bodyRequestVal1.setConductor("Conductor-883514974");
        _itemSearch_bodyRequestVal1.setDirector("Director-1929325110");
        _itemSearch_bodyRequestVal1.setItemPage(new java.math.BigInteger("53472811653613688728656600796273795204"));
        _itemSearch_bodyRequestVal1.setKeywords("Keywords-366467908");
        _itemSearch_bodyRequestVal1.setManufacturer("Manufacturer-1318134730");
        _itemSearch_bodyRequestVal1.setMaximumPrice(new java.math.BigInteger("-314456031617855825409721913052729872"));
        _itemSearch_bodyRequestVal1.setMerchantId("MerchantId1097668758");
        _itemSearch_bodyRequestVal1.setMinimumPrice(new java.math.BigInteger("-73739549167968119581775610724493527174"));
        _itemSearch_bodyRequestVal1.setMinPercentageOff(new java.math.BigInteger("77407491799632676562619320223285082080"));
        _itemSearch_bodyRequestVal1.setMusicLabel("MusicLabel-1359342175");
        _itemSearch_bodyRequestVal1.setOrchestra("Orchestra1010155924");
        _itemSearch_bodyRequestVal1.setPower("Power1319934989");
        _itemSearch_bodyRequestVal1.setPublisher("Publisher-819115707");
        _itemSearch_bodyRequestVal1.setRelatedItemPage("RelatedItemPage2039697453");
        java.util.List<java.lang.String> _itemSearch_bodyRequestVal1RelationshipType = new java.util.ArrayList<java.lang.String>();
        _itemSearch_bodyRequestVal1.getRelationshipType().addAll(_itemSearch_bodyRequestVal1RelationshipType);
        java.util.List<java.lang.String> _itemSearch_bodyRequestVal1ResponseGroup = new java.util.ArrayList<java.lang.String>();
        _itemSearch_bodyRequestVal1.getResponseGroup().addAll(_itemSearch_bodyRequestVal1ResponseGroup);
        _itemSearch_bodyRequestVal1.setSearchIndex("SearchIndex-598992109");
        _itemSearch_bodyRequestVal1.setSort("Sort1754093449");
        _itemSearch_bodyRequestVal1.setTitle("Title-739969239");
        _itemSearch_bodyRequestVal1.setReleaseDate("ReleaseDate244717836");
        _itemSearch_bodyRequestVal1.setIncludeReviewsSummary("IncludeReviewsSummary-158450683");
        _itemSearch_bodyRequestVal1.setTruncateReviewsAt(new java.math.BigInteger("-6673373306917306917914991323473007406"));
        _itemSearch_bodyRequest.add(_itemSearch_bodyRequestVal1);
        _itemSearch_body.getRequest().addAll(_itemSearch_bodyRequest);
        com.amazon.webservices.awsecommerceservice.ItemSearchResponse _itemSearch__return = port.itemSearch(_itemSearch_body);
        System.out.println("itemSearch.result=" + _itemSearch__return);


        }
        {
        System.out.println("Invoking cartClear...");
        com.amazon.webservices.awsecommerceservice.CartClear _cartClear_body = new com.amazon.webservices.awsecommerceservice.CartClear();
        _cartClear_body.setMarketplaceDomain("MarketplaceDomain389421567");
        _cartClear_body.setAWSAccessKeyId("AWSAccessKeyId-473951601");
        _cartClear_body.setAssociateTag("AssociateTag1810346943");
        _cartClear_body.setValidate("Validate-366981367");
        _cartClear_body.setXMLEscaping("XMLEscaping1085894735");
        com.amazon.webservices.awsecommerceservice.CartClearRequest _cartClear_bodyShared = new com.amazon.webservices.awsecommerceservice.CartClearRequest();
        _cartClear_bodyShared.setCartId("CartId772313009");
        _cartClear_bodyShared.setHMAC("HMAC-627937926");
        _cartClear_bodyShared.setMergeCart("MergeCart-914169947");
        java.util.List<java.lang.String> _cartClear_bodySharedResponseGroup = new java.util.ArrayList<java.lang.String>();
        java.lang.String _cartClear_bodySharedResponseGroupVal1 = "_cartClear_bodySharedResponseGroupVal-959574720";
        _cartClear_bodySharedResponseGroup.add(_cartClear_bodySharedResponseGroupVal1);
        _cartClear_bodyShared.getResponseGroup().addAll(_cartClear_bodySharedResponseGroup);
        _cartClear_body.setShared(_cartClear_bodyShared);
        java.util.List<com.amazon.webservices.awsecommerceservice.CartClearRequest> _cartClear_bodyRequest = new java.util.ArrayList<com.amazon.webservices.awsecommerceservice.CartClearRequest>();
        com.amazon.webservices.awsecommerceservice.CartClearRequest _cartClear_bodyRequestVal1 = new com.amazon.webservices.awsecommerceservice.CartClearRequest();
        _cartClear_bodyRequestVal1.setCartId("CartId-1866506727");
        _cartClear_bodyRequestVal1.setHMAC("HMAC881139773");
        _cartClear_bodyRequestVal1.setMergeCart("MergeCart817027473");
        java.util.List<java.lang.String> _cartClear_bodyRequestVal1ResponseGroup = new java.util.ArrayList<java.lang.String>();
        _cartClear_bodyRequestVal1.getResponseGroup().addAll(_cartClear_bodyRequestVal1ResponseGroup);
        _cartClear_bodyRequest.add(_cartClear_bodyRequestVal1);
        _cartClear_body.getRequest().addAll(_cartClear_bodyRequest);
        com.amazon.webservices.awsecommerceservice.CartClearResponse _cartClear__return = port.cartClear(_cartClear_body);
        System.out.println("cartClear.result=" + _cartClear__return);


        }

        System.exit(0);
    }

}
