
package com.amazon.webservices.awsecommerceservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.1.16
 * 2018-10-05T17:30:35.136+05:30
 * Generated source version: 3.1.16
 * 
 */
public final class AWSECommerceServicePortType_AWSECommerceServicePortES_Client {

    private static final QName SERVICE_NAME = new QName("http://webservices.amazon.com/AWSECommerceService/2011-08-01", "AWSECommerceService");

    private AWSECommerceServicePortType_AWSECommerceServicePortES_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = AWSECommerceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        AWSECommerceService ss = new AWSECommerceService(wsdlURL, SERVICE_NAME);
        AWSECommerceServicePortType port = ss.getAWSECommerceServicePortES();  
        
        {
        System.out.println("Invoking cartCreate...");
        com.amazon.webservices.awsecommerceservice.CartCreate _cartCreate_body = new com.amazon.webservices.awsecommerceservice.CartCreate();
        _cartCreate_body.setMarketplaceDomain("MarketplaceDomain1130194732");
        _cartCreate_body.setAWSAccessKeyId("AWSAccessKeyId1360991444");
        _cartCreate_body.setAssociateTag("AssociateTag-827501635");
        _cartCreate_body.setValidate("Validate1104628422");
        _cartCreate_body.setXMLEscaping("XMLEscaping1409647602");
        com.amazon.webservices.awsecommerceservice.CartCreateRequest _cartCreate_bodyShared = new com.amazon.webservices.awsecommerceservice.CartCreateRequest();
        _cartCreate_bodyShared.setMergeCart("MergeCart-478062933");
        com.amazon.webservices.awsecommerceservice.CartCreateRequest.Items _cartCreate_bodySharedItems = new com.amazon.webservices.awsecommerceservice.CartCreateRequest.Items();
        java.util.List<com.amazon.webservices.awsecommerceservice.CartCreateRequest.Items.Item> _cartCreate_bodySharedItemsItem = new java.util.ArrayList<com.amazon.webservices.awsecommerceservice.CartCreateRequest.Items.Item>();
        _cartCreate_bodySharedItems.getItem().addAll(_cartCreate_bodySharedItemsItem);
        _cartCreate_bodyShared.setItems(_cartCreate_bodySharedItems);
        java.util.List<java.lang.String> _cartCreate_bodySharedResponseGroup = new java.util.ArrayList<java.lang.String>();
        java.lang.String _cartCreate_bodySharedResponseGroupVal1 = "_cartCreate_bodySharedResponseGroupVal1809634178";
        _cartCreate_bodySharedResponseGroup.add(_cartCreate_bodySharedResponseGroupVal1);
        _cartCreate_bodyShared.getResponseGroup().addAll(_cartCreate_bodySharedResponseGroup);
        _cartCreate_body.setShared(_cartCreate_bodyShared);
        java.util.List<com.amazon.webservices.awsecommerceservice.CartCreateRequest> _cartCreate_bodyRequest = new java.util.ArrayList<com.amazon.webservices.awsecommerceservice.CartCreateRequest>();
        com.amazon.webservices.awsecommerceservice.CartCreateRequest _cartCreate_bodyRequestVal1 = new com.amazon.webservices.awsecommerceservice.CartCreateRequest();
        _cartCreate_bodyRequestVal1.setMergeCart("MergeCart-1751793177");
        com.amazon.webservices.awsecommerceservice.CartCreateRequest.Items _cartCreate_bodyRequestVal1Items = new com.amazon.webservices.awsecommerceservice.CartCreateRequest.Items();
        java.util.List<com.amazon.webservices.awsecommerceservice.CartCreateRequest.Items.Item> _cartCreate_bodyRequestVal1ItemsItem = new java.util.ArrayList<com.amazon.webservices.awsecommerceservice.CartCreateRequest.Items.Item>();
        _cartCreate_bodyRequestVal1Items.getItem().addAll(_cartCreate_bodyRequestVal1ItemsItem);
        _cartCreate_bodyRequestVal1.setItems(_cartCreate_bodyRequestVal1Items);
        java.util.List<java.lang.String> _cartCreate_bodyRequestVal1ResponseGroup = new java.util.ArrayList<java.lang.String>();
        _cartCreate_bodyRequestVal1.getResponseGroup().addAll(_cartCreate_bodyRequestVal1ResponseGroup);
        _cartCreate_bodyRequest.add(_cartCreate_bodyRequestVal1);
        _cartCreate_body.getRequest().addAll(_cartCreate_bodyRequest);
        com.amazon.webservices.awsecommerceservice.CartCreateResponse _cartCreate__return = port.cartCreate(_cartCreate_body);
        System.out.println("cartCreate.result=" + _cartCreate__return);


        }
        {
        System.out.println("Invoking browseNodeLookup...");
        com.amazon.webservices.awsecommerceservice.BrowseNodeLookup _browseNodeLookup_body = new com.amazon.webservices.awsecommerceservice.BrowseNodeLookup();
        _browseNodeLookup_body.setMarketplaceDomain("MarketplaceDomain-1446264347");
        _browseNodeLookup_body.setAWSAccessKeyId("AWSAccessKeyId899566951");
        _browseNodeLookup_body.setAssociateTag("AssociateTag499641707");
        _browseNodeLookup_body.setValidate("Validate619002600");
        _browseNodeLookup_body.setXMLEscaping("XMLEscaping-452681567");
        com.amazon.webservices.awsecommerceservice.BrowseNodeLookupRequest _browseNodeLookup_bodyShared = new com.amazon.webservices.awsecommerceservice.BrowseNodeLookupRequest();
        java.util.List<java.lang.String> _browseNodeLookup_bodySharedBrowseNodeId = new java.util.ArrayList<java.lang.String>();
        java.lang.String _browseNodeLookup_bodySharedBrowseNodeIdVal1 = "_browseNodeLookup_bodySharedBrowseNodeIdVal460544935";
        _browseNodeLookup_bodySharedBrowseNodeId.add(_browseNodeLookup_bodySharedBrowseNodeIdVal1);
        _browseNodeLookup_bodyShared.getBrowseNodeId().addAll(_browseNodeLookup_bodySharedBrowseNodeId);
        java.util.List<java.lang.String> _browseNodeLookup_bodySharedResponseGroup = new java.util.ArrayList<java.lang.String>();
        java.lang.String _browseNodeLookup_bodySharedResponseGroupVal1 = "_browseNodeLookup_bodySharedResponseGroupVal-165769223";
        _browseNodeLookup_bodySharedResponseGroup.add(_browseNodeLookup_bodySharedResponseGroupVal1);
        _browseNodeLookup_bodyShared.getResponseGroup().addAll(_browseNodeLookup_bodySharedResponseGroup);
        _browseNodeLookup_body.setShared(_browseNodeLookup_bodyShared);
        java.util.List<com.amazon.webservices.awsecommerceservice.BrowseNodeLookupRequest> _browseNodeLookup_bodyRequest = new java.util.ArrayList<com.amazon.webservices.awsecommerceservice.BrowseNodeLookupRequest>();
        com.amazon.webservices.awsecommerceservice.BrowseNodeLookupRequest _browseNodeLookup_bodyRequestVal1 = new com.amazon.webservices.awsecommerceservice.BrowseNodeLookupRequest();
        java.util.List<java.lang.String> _browseNodeLookup_bodyRequestVal1BrowseNodeId = new java.util.ArrayList<java.lang.String>();
        _browseNodeLookup_bodyRequestVal1.getBrowseNodeId().addAll(_browseNodeLookup_bodyRequestVal1BrowseNodeId);
        java.util.List<java.lang.String> _browseNodeLookup_bodyRequestVal1ResponseGroup = new java.util.ArrayList<java.lang.String>();
        _browseNodeLookup_bodyRequestVal1.getResponseGroup().addAll(_browseNodeLookup_bodyRequestVal1ResponseGroup);
        _browseNodeLookup_bodyRequest.add(_browseNodeLookup_bodyRequestVal1);
        _browseNodeLookup_body.getRequest().addAll(_browseNodeLookup_bodyRequest);
        com.amazon.webservices.awsecommerceservice.BrowseNodeLookupResponse _browseNodeLookup__return = port.browseNodeLookup(_browseNodeLookup_body);
        System.out.println("browseNodeLookup.result=" + _browseNodeLookup__return);


        }
        {
        System.out.println("Invoking cartGet...");
        com.amazon.webservices.awsecommerceservice.CartGet _cartGet_body = new com.amazon.webservices.awsecommerceservice.CartGet();
        _cartGet_body.setMarketplaceDomain("MarketplaceDomain-160244261");
        _cartGet_body.setAWSAccessKeyId("AWSAccessKeyId1877043470");
        _cartGet_body.setAssociateTag("AssociateTag-877120362");
        _cartGet_body.setValidate("Validate-684447226");
        _cartGet_body.setXMLEscaping("XMLEscaping1196704265");
        com.amazon.webservices.awsecommerceservice.CartGetRequest _cartGet_bodyShared = new com.amazon.webservices.awsecommerceservice.CartGetRequest();
        _cartGet_bodyShared.setCartId("CartId1587457746");
        _cartGet_bodyShared.setHMAC("HMAC183120457");
        _cartGet_bodyShared.setMergeCart("MergeCart1403079521");
        java.util.List<java.lang.String> _cartGet_bodySharedResponseGroup = new java.util.ArrayList<java.lang.String>();
        java.lang.String _cartGet_bodySharedResponseGroupVal1 = "_cartGet_bodySharedResponseGroupVal1334691058";
        _cartGet_bodySharedResponseGroup.add(_cartGet_bodySharedResponseGroupVal1);
        _cartGet_bodyShared.getResponseGroup().addAll(_cartGet_bodySharedResponseGroup);
        _cartGet_body.setShared(_cartGet_bodyShared);
        java.util.List<com.amazon.webservices.awsecommerceservice.CartGetRequest> _cartGet_bodyRequest = new java.util.ArrayList<com.amazon.webservices.awsecommerceservice.CartGetRequest>();
        com.amazon.webservices.awsecommerceservice.CartGetRequest _cartGet_bodyRequestVal1 = new com.amazon.webservices.awsecommerceservice.CartGetRequest();
        _cartGet_bodyRequestVal1.setCartId("CartId-1063979769");
        _cartGet_bodyRequestVal1.setHMAC("HMAC-1857278358");
        _cartGet_bodyRequestVal1.setMergeCart("MergeCart-402244963");
        java.util.List<java.lang.String> _cartGet_bodyRequestVal1ResponseGroup = new java.util.ArrayList<java.lang.String>();
        _cartGet_bodyRequestVal1.getResponseGroup().addAll(_cartGet_bodyRequestVal1ResponseGroup);
        _cartGet_bodyRequest.add(_cartGet_bodyRequestVal1);
        _cartGet_body.getRequest().addAll(_cartGet_bodyRequest);
        com.amazon.webservices.awsecommerceservice.CartGetResponse _cartGet__return = port.cartGet(_cartGet_body);
        System.out.println("cartGet.result=" + _cartGet__return);


        }
        {
        System.out.println("Invoking cartModify...");
        com.amazon.webservices.awsecommerceservice.CartModify _cartModify_body = new com.amazon.webservices.awsecommerceservice.CartModify();
        _cartModify_body.setMarketplaceDomain("MarketplaceDomain-1510421102");
        _cartModify_body.setAWSAccessKeyId("AWSAccessKeyId711092781");
        _cartModify_body.setAssociateTag("AssociateTag980992283");
        _cartModify_body.setValidate("Validate1392546854");
        _cartModify_body.setXMLEscaping("XMLEscaping1597276134");
        com.amazon.webservices.awsecommerceservice.CartModifyRequest _cartModify_bodyShared = new com.amazon.webservices.awsecommerceservice.CartModifyRequest();
        _cartModify_bodyShared.setCartId("CartId425717602");
        _cartModify_bodyShared.setHMAC("HMAC1050610196");
        _cartModify_bodyShared.setMergeCart("MergeCart905135764");
        com.amazon.webservices.awsecommerceservice.CartModifyRequest.Items _cartModify_bodySharedItems = new com.amazon.webservices.awsecommerceservice.CartModifyRequest.Items();
        java.util.List<com.amazon.webservices.awsecommerceservice.CartModifyRequest.Items.Item> _cartModify_bodySharedItemsItem = new java.util.ArrayList<com.amazon.webservices.awsecommerceservice.CartModifyRequest.Items.Item>();
        _cartModify_bodySharedItems.getItem().addAll(_cartModify_bodySharedItemsItem);
        _cartModify_bodyShared.setItems(_cartModify_bodySharedItems);
        java.util.List<java.lang.String> _cartModify_bodySharedResponseGroup = new java.util.ArrayList<java.lang.String>();
        java.lang.String _cartModify_bodySharedResponseGroupVal1 = "_cartModify_bodySharedResponseGroupVal-1527798611";
        _cartModify_bodySharedResponseGroup.add(_cartModify_bodySharedResponseGroupVal1);
        _cartModify_bodyShared.getResponseGroup().addAll(_cartModify_bodySharedResponseGroup);
        _cartModify_body.setShared(_cartModify_bodyShared);
        java.util.List<com.amazon.webservices.awsecommerceservice.CartModifyRequest> _cartModify_bodyRequest = new java.util.ArrayList<com.amazon.webservices.awsecommerceservice.CartModifyRequest>();
        com.amazon.webservices.awsecommerceservice.CartModifyRequest _cartModify_bodyRequestVal1 = new com.amazon.webservices.awsecommerceservice.CartModifyRequest();
        _cartModify_bodyRequestVal1.setCartId("CartId1694686928");
        _cartModify_bodyRequestVal1.setHMAC("HMAC-597661683");
        _cartModify_bodyRequestVal1.setMergeCart("MergeCart1667334211");
        com.amazon.webservices.awsecommerceservice.CartModifyRequest.Items _cartModify_bodyRequestVal1Items = new com.amazon.webservices.awsecommerceservice.CartModifyRequest.Items();
        java.util.List<com.amazon.webservices.awsecommerceservice.CartModifyRequest.Items.Item> _cartModify_bodyRequestVal1ItemsItem = new java.util.ArrayList<com.amazon.webservices.awsecommerceservice.CartModifyRequest.Items.Item>();
        _cartModify_bodyRequestVal1Items.getItem().addAll(_cartModify_bodyRequestVal1ItemsItem);
        _cartModify_bodyRequestVal1.setItems(_cartModify_bodyRequestVal1Items);
        java.util.List<java.lang.String> _cartModify_bodyRequestVal1ResponseGroup = new java.util.ArrayList<java.lang.String>();
        _cartModify_bodyRequestVal1.getResponseGroup().addAll(_cartModify_bodyRequestVal1ResponseGroup);
        _cartModify_bodyRequest.add(_cartModify_bodyRequestVal1);
        _cartModify_body.getRequest().addAll(_cartModify_bodyRequest);
        com.amazon.webservices.awsecommerceservice.CartModifyResponse _cartModify__return = port.cartModify(_cartModify_body);
        System.out.println("cartModify.result=" + _cartModify__return);


        }
        {
        System.out.println("Invoking cartAdd...");
        com.amazon.webservices.awsecommerceservice.CartAdd _cartAdd_body = new com.amazon.webservices.awsecommerceservice.CartAdd();
        _cartAdd_body.setMarketplaceDomain("MarketplaceDomain545442163");
        _cartAdd_body.setAWSAccessKeyId("AWSAccessKeyId384845158");
        _cartAdd_body.setAssociateTag("AssociateTag-389561757");
        _cartAdd_body.setValidate("Validate1922196003");
        _cartAdd_body.setXMLEscaping("XMLEscaping-1648501558");
        com.amazon.webservices.awsecommerceservice.CartAddRequest _cartAdd_bodyShared = new com.amazon.webservices.awsecommerceservice.CartAddRequest();
        _cartAdd_bodyShared.setCartId("CartId2107474890");
        _cartAdd_bodyShared.setHMAC("HMAC121194741");
        _cartAdd_bodyShared.setMergeCart("MergeCart-1791194165");
        com.amazon.webservices.awsecommerceservice.CartAddRequest.Items _cartAdd_bodySharedItems = new com.amazon.webservices.awsecommerceservice.CartAddRequest.Items();
        java.util.List<com.amazon.webservices.awsecommerceservice.CartAddRequest.Items.Item> _cartAdd_bodySharedItemsItem = new java.util.ArrayList<com.amazon.webservices.awsecommerceservice.CartAddRequest.Items.Item>();
        _cartAdd_bodySharedItems.getItem().addAll(_cartAdd_bodySharedItemsItem);
        _cartAdd_bodyShared.setItems(_cartAdd_bodySharedItems);
        java.util.List<java.lang.String> _cartAdd_bodySharedResponseGroup = new java.util.ArrayList<java.lang.String>();
        java.lang.String _cartAdd_bodySharedResponseGroupVal1 = "_cartAdd_bodySharedResponseGroupVal-1623405862";
        _cartAdd_bodySharedResponseGroup.add(_cartAdd_bodySharedResponseGroupVal1);
        _cartAdd_bodyShared.getResponseGroup().addAll(_cartAdd_bodySharedResponseGroup);
        _cartAdd_body.setShared(_cartAdd_bodyShared);
        java.util.List<com.amazon.webservices.awsecommerceservice.CartAddRequest> _cartAdd_bodyRequest = new java.util.ArrayList<com.amazon.webservices.awsecommerceservice.CartAddRequest>();
        com.amazon.webservices.awsecommerceservice.CartAddRequest _cartAdd_bodyRequestVal1 = new com.amazon.webservices.awsecommerceservice.CartAddRequest();
        _cartAdd_bodyRequestVal1.setCartId("CartId447056525");
        _cartAdd_bodyRequestVal1.setHMAC("HMAC1338232399");
        _cartAdd_bodyRequestVal1.setMergeCart("MergeCart-799681324");
        com.amazon.webservices.awsecommerceservice.CartAddRequest.Items _cartAdd_bodyRequestVal1Items = new com.amazon.webservices.awsecommerceservice.CartAddRequest.Items();
        java.util.List<com.amazon.webservices.awsecommerceservice.CartAddRequest.Items.Item> _cartAdd_bodyRequestVal1ItemsItem = new java.util.ArrayList<com.amazon.webservices.awsecommerceservice.CartAddRequest.Items.Item>();
        _cartAdd_bodyRequestVal1Items.getItem().addAll(_cartAdd_bodyRequestVal1ItemsItem);
        _cartAdd_bodyRequestVal1.setItems(_cartAdd_bodyRequestVal1Items);
        java.util.List<java.lang.String> _cartAdd_bodyRequestVal1ResponseGroup = new java.util.ArrayList<java.lang.String>();
        _cartAdd_bodyRequestVal1.getResponseGroup().addAll(_cartAdd_bodyRequestVal1ResponseGroup);
        _cartAdd_bodyRequest.add(_cartAdd_bodyRequestVal1);
        _cartAdd_body.getRequest().addAll(_cartAdd_bodyRequest);
        com.amazon.webservices.awsecommerceservice.CartAddResponse _cartAdd__return = port.cartAdd(_cartAdd_body);
        System.out.println("cartAdd.result=" + _cartAdd__return);


        }
        {
        System.out.println("Invoking itemLookup...");
        com.amazon.webservices.awsecommerceservice.ItemLookup _itemLookup_body = new com.amazon.webservices.awsecommerceservice.ItemLookup();
        _itemLookup_body.setMarketplaceDomain("MarketplaceDomain-523575780");
        _itemLookup_body.setAWSAccessKeyId("AWSAccessKeyId-1665587808");
        _itemLookup_body.setAssociateTag("AssociateTag-987029494");
        _itemLookup_body.setValidate("Validate-1105934492");
        _itemLookup_body.setXMLEscaping("XMLEscaping-1634408350");
        com.amazon.webservices.awsecommerceservice.ItemLookupRequest _itemLookup_bodyShared = new com.amazon.webservices.awsecommerceservice.ItemLookupRequest();
        _itemLookup_bodyShared.setCondition("Condition-2004612346");
        _itemLookup_bodyShared.setIdType("IdType-1349189262");
        _itemLookup_bodyShared.setMerchantId("MerchantId-638144503");
        java.util.List<java.lang.String> _itemLookup_bodySharedItemId = new java.util.ArrayList<java.lang.String>();
        java.lang.String _itemLookup_bodySharedItemIdVal1 = "_itemLookup_bodySharedItemIdVal-714704870";
        _itemLookup_bodySharedItemId.add(_itemLookup_bodySharedItemIdVal1);
        _itemLookup_bodyShared.getItemId().addAll(_itemLookup_bodySharedItemId);
        java.util.List<java.lang.String> _itemLookup_bodySharedResponseGroup = new java.util.ArrayList<java.lang.String>();
        java.lang.String _itemLookup_bodySharedResponseGroupVal1 = "_itemLookup_bodySharedResponseGroupVal-1555586870";
        _itemLookup_bodySharedResponseGroup.add(_itemLookup_bodySharedResponseGroupVal1);
        _itemLookup_bodyShared.getResponseGroup().addAll(_itemLookup_bodySharedResponseGroup);
        _itemLookup_bodyShared.setSearchIndex("SearchIndex590916713");
        _itemLookup_bodyShared.setVariationPage("VariationPage292968135");
        _itemLookup_bodyShared.setRelatedItemPage("RelatedItemPage19832274");
        java.util.List<java.lang.String> _itemLookup_bodySharedRelationshipType = new java.util.ArrayList<java.lang.String>();
        java.lang.String _itemLookup_bodySharedRelationshipTypeVal1 = "_itemLookup_bodySharedRelationshipTypeVal-393761229";
        _itemLookup_bodySharedRelationshipType.add(_itemLookup_bodySharedRelationshipTypeVal1);
        _itemLookup_bodyShared.getRelationshipType().addAll(_itemLookup_bodySharedRelationshipType);
        _itemLookup_bodyShared.setIncludeReviewsSummary("IncludeReviewsSummary906689674");
        _itemLookup_bodyShared.setTruncateReviewsAt(new java.math.BigInteger("53538535640355978227983637257647052655"));
        _itemLookup_body.setShared(_itemLookup_bodyShared);
        java.util.List<com.amazon.webservices.awsecommerceservice.ItemLookupRequest> _itemLookup_bodyRequest = new java.util.ArrayList<com.amazon.webservices.awsecommerceservice.ItemLookupRequest>();
        com.amazon.webservices.awsecommerceservice.ItemLookupRequest _itemLookup_bodyRequestVal1 = new com.amazon.webservices.awsecommerceservice.ItemLookupRequest();
        _itemLookup_bodyRequestVal1.setCondition("Condition-1294581950");
        _itemLookup_bodyRequestVal1.setIdType("IdType1458596601");
        _itemLookup_bodyRequestVal1.setMerchantId("MerchantId-377444052");
        java.util.List<java.lang.String> _itemLookup_bodyRequestVal1ItemId = new java.util.ArrayList<java.lang.String>();
        _itemLookup_bodyRequestVal1.getItemId().addAll(_itemLookup_bodyRequestVal1ItemId);
        java.util.List<java.lang.String> _itemLookup_bodyRequestVal1ResponseGroup = new java.util.ArrayList<java.lang.String>();
        _itemLookup_bodyRequestVal1.getResponseGroup().addAll(_itemLookup_bodyRequestVal1ResponseGroup);
        _itemLookup_bodyRequestVal1.setSearchIndex("SearchIndex286928377");
        _itemLookup_bodyRequestVal1.setVariationPage("VariationPage-942895716");
        _itemLookup_bodyRequestVal1.setRelatedItemPage("RelatedItemPage819700553");
        java.util.List<java.lang.String> _itemLookup_bodyRequestVal1RelationshipType = new java.util.ArrayList<java.lang.String>();
        _itemLookup_bodyRequestVal1.getRelationshipType().addAll(_itemLookup_bodyRequestVal1RelationshipType);
        _itemLookup_bodyRequestVal1.setIncludeReviewsSummary("IncludeReviewsSummary-901123131");
        _itemLookup_bodyRequestVal1.setTruncateReviewsAt(new java.math.BigInteger("-21213857522564776423852495397702598971"));
        _itemLookup_bodyRequest.add(_itemLookup_bodyRequestVal1);
        _itemLookup_body.getRequest().addAll(_itemLookup_bodyRequest);
        com.amazon.webservices.awsecommerceservice.ItemLookupResponse _itemLookup__return = port.itemLookup(_itemLookup_body);
        System.out.println("itemLookup.result=" + _itemLookup__return);


        }
        {
        System.out.println("Invoking similarityLookup...");
        com.amazon.webservices.awsecommerceservice.SimilarityLookup _similarityLookup_body = new com.amazon.webservices.awsecommerceservice.SimilarityLookup();
        _similarityLookup_body.setMarketplaceDomain("MarketplaceDomain-471702971");
        _similarityLookup_body.setAWSAccessKeyId("AWSAccessKeyId-735687073");
        _similarityLookup_body.setAssociateTag("AssociateTag-2023329731");
        _similarityLookup_body.setValidate("Validate-8928566");
        _similarityLookup_body.setXMLEscaping("XMLEscaping2109179441");
        com.amazon.webservices.awsecommerceservice.SimilarityLookupRequest _similarityLookup_bodyShared = new com.amazon.webservices.awsecommerceservice.SimilarityLookupRequest();
        _similarityLookup_bodyShared.setCondition("Condition1047109528");
        java.util.List<java.lang.String> _similarityLookup_bodySharedItemId = new java.util.ArrayList<java.lang.String>();
        java.lang.String _similarityLookup_bodySharedItemIdVal1 = "_similarityLookup_bodySharedItemIdVal138042033";
        _similarityLookup_bodySharedItemId.add(_similarityLookup_bodySharedItemIdVal1);
        _similarityLookup_bodyShared.getItemId().addAll(_similarityLookup_bodySharedItemId);
        _similarityLookup_bodyShared.setMerchantId("MerchantId1446633054");
        java.util.List<java.lang.String> _similarityLookup_bodySharedResponseGroup = new java.util.ArrayList<java.lang.String>();
        java.lang.String _similarityLookup_bodySharedResponseGroupVal1 = "_similarityLookup_bodySharedResponseGroupVal1388766360";
        _similarityLookup_bodySharedResponseGroup.add(_similarityLookup_bodySharedResponseGroupVal1);
        _similarityLookup_bodyShared.getResponseGroup().addAll(_similarityLookup_bodySharedResponseGroup);
        _similarityLookup_bodyShared.setSimilarityType("SimilarityType364794218");
        _similarityLookup_body.setShared(_similarityLookup_bodyShared);
        java.util.List<com.amazon.webservices.awsecommerceservice.SimilarityLookupRequest> _similarityLookup_bodyRequest = new java.util.ArrayList<com.amazon.webservices.awsecommerceservice.SimilarityLookupRequest>();
        com.amazon.webservices.awsecommerceservice.SimilarityLookupRequest _similarityLookup_bodyRequestVal1 = new com.amazon.webservices.awsecommerceservice.SimilarityLookupRequest();
        _similarityLookup_bodyRequestVal1.setCondition("Condition2002970210");
        java.util.List<java.lang.String> _similarityLookup_bodyRequestVal1ItemId = new java.util.ArrayList<java.lang.String>();
        _similarityLookup_bodyRequestVal1.getItemId().addAll(_similarityLookup_bodyRequestVal1ItemId);
        _similarityLookup_bodyRequestVal1.setMerchantId("MerchantId2042855054");
        java.util.List<java.lang.String> _similarityLookup_bodyRequestVal1ResponseGroup = new java.util.ArrayList<java.lang.String>();
        _similarityLookup_bodyRequestVal1.getResponseGroup().addAll(_similarityLookup_bodyRequestVal1ResponseGroup);
        _similarityLookup_bodyRequestVal1.setSimilarityType("SimilarityType259154462");
        _similarityLookup_bodyRequest.add(_similarityLookup_bodyRequestVal1);
        _similarityLookup_body.getRequest().addAll(_similarityLookup_bodyRequest);
        com.amazon.webservices.awsecommerceservice.SimilarityLookupResponse _similarityLookup__return = port.similarityLookup(_similarityLookup_body);
        System.out.println("similarityLookup.result=" + _similarityLookup__return);


        }
        {
        System.out.println("Invoking itemSearch...");
        com.amazon.webservices.awsecommerceservice.ItemSearch _itemSearch_body = new com.amazon.webservices.awsecommerceservice.ItemSearch();
        _itemSearch_body.setMarketplaceDomain("MarketplaceDomain235678836");
        _itemSearch_body.setAWSAccessKeyId("AWSAccessKeyId-709181072");
        _itemSearch_body.setAssociateTag("AssociateTag-1944867383");
        _itemSearch_body.setXMLEscaping("XMLEscaping1094332224");
        _itemSearch_body.setValidate("Validate1576688323");
        com.amazon.webservices.awsecommerceservice.ItemSearchRequest _itemSearch_bodyShared = new com.amazon.webservices.awsecommerceservice.ItemSearchRequest();
        _itemSearch_bodyShared.setActor("Actor-1890042623");
        _itemSearch_bodyShared.setArtist("Artist594456782");
        _itemSearch_bodyShared.setAvailability("Availability-469072964");
        java.util.List<java.lang.String> _itemSearch_bodySharedAudienceRating = new java.util.ArrayList<java.lang.String>();
        java.lang.String _itemSearch_bodySharedAudienceRatingVal1 = "_itemSearch_bodySharedAudienceRatingVal932448614";
        _itemSearch_bodySharedAudienceRating.add(_itemSearch_bodySharedAudienceRatingVal1);
        _itemSearch_bodyShared.getAudienceRating().addAll(_itemSearch_bodySharedAudienceRating);
        _itemSearch_bodyShared.setAuthor("Author255922498");
        _itemSearch_bodyShared.setBrand("Brand-608955295");
        _itemSearch_bodyShared.setBrowseNode("BrowseNode1310665776");
        _itemSearch_bodyShared.setComposer("Composer1956450112");
        _itemSearch_bodyShared.setCondition("Condition-792207956");
        _itemSearch_bodyShared.setConductor("Conductor-216309189");
        _itemSearch_bodyShared.setDirector("Director-538980863");
        _itemSearch_bodyShared.setItemPage(new java.math.BigInteger("-61582006673162297524598933062596822398"));
        _itemSearch_bodyShared.setKeywords("Keywords-1112950003");
        _itemSearch_bodyShared.setManufacturer("Manufacturer-192943948");
        _itemSearch_bodyShared.setMaximumPrice(new java.math.BigInteger("54745530288798930608986696774681835353"));
        _itemSearch_bodyShared.setMerchantId("MerchantId-1641697223");
        _itemSearch_bodyShared.setMinimumPrice(new java.math.BigInteger("-43475152791188008542308598048152301344"));
        _itemSearch_bodyShared.setMinPercentageOff(new java.math.BigInteger("-12659592658838125881596129662241919926"));
        _itemSearch_bodyShared.setMusicLabel("MusicLabel-2058745538");
        _itemSearch_bodyShared.setOrchestra("Orchestra-1804450581");
        _itemSearch_bodyShared.setPower("Power-307831809");
        _itemSearch_bodyShared.setPublisher("Publisher-894589633");
        _itemSearch_bodyShared.setRelatedItemPage("RelatedItemPage-2031040231");
        java.util.List<java.lang.String> _itemSearch_bodySharedRelationshipType = new java.util.ArrayList<java.lang.String>();
        java.lang.String _itemSearch_bodySharedRelationshipTypeVal1 = "_itemSearch_bodySharedRelationshipTypeVal-307598441";
        _itemSearch_bodySharedRelationshipType.add(_itemSearch_bodySharedRelationshipTypeVal1);
        _itemSearch_bodyShared.getRelationshipType().addAll(_itemSearch_bodySharedRelationshipType);
        java.util.List<java.lang.String> _itemSearch_bodySharedResponseGroup = new java.util.ArrayList<java.lang.String>();
        java.lang.String _itemSearch_bodySharedResponseGroupVal1 = "_itemSearch_bodySharedResponseGroupVal-1433654505";
        _itemSearch_bodySharedResponseGroup.add(_itemSearch_bodySharedResponseGroupVal1);
        _itemSearch_bodyShared.getResponseGroup().addAll(_itemSearch_bodySharedResponseGroup);
        _itemSearch_bodyShared.setSearchIndex("SearchIndex-496213461");
        _itemSearch_bodyShared.setSort("Sort-2017002223");
        _itemSearch_bodyShared.setTitle("Title188111478");
        _itemSearch_bodyShared.setReleaseDate("ReleaseDate-1534255301");
        _itemSearch_bodyShared.setIncludeReviewsSummary("IncludeReviewsSummary1313158356");
        _itemSearch_bodyShared.setTruncateReviewsAt(new java.math.BigInteger("51346520193293523041246205416062012729"));
        _itemSearch_body.setShared(_itemSearch_bodyShared);
        java.util.List<com.amazon.webservices.awsecommerceservice.ItemSearchRequest> _itemSearch_bodyRequest = new java.util.ArrayList<com.amazon.webservices.awsecommerceservice.ItemSearchRequest>();
        com.amazon.webservices.awsecommerceservice.ItemSearchRequest _itemSearch_bodyRequestVal1 = new com.amazon.webservices.awsecommerceservice.ItemSearchRequest();
        _itemSearch_bodyRequestVal1.setActor("Actor1017639170");
        _itemSearch_bodyRequestVal1.setArtist("Artist18256712");
        _itemSearch_bodyRequestVal1.setAvailability("Availability-1017775159");
        java.util.List<java.lang.String> _itemSearch_bodyRequestVal1AudienceRating = new java.util.ArrayList<java.lang.String>();
        _itemSearch_bodyRequestVal1.getAudienceRating().addAll(_itemSearch_bodyRequestVal1AudienceRating);
        _itemSearch_bodyRequestVal1.setAuthor("Author-1807098155");
        _itemSearch_bodyRequestVal1.setBrand("Brand-233990708");
        _itemSearch_bodyRequestVal1.setBrowseNode("BrowseNode-2065759179");
        _itemSearch_bodyRequestVal1.setComposer("Composer1898504972");
        _itemSearch_bodyRequestVal1.setCondition("Condition-1619626563");
        _itemSearch_bodyRequestVal1.setConductor("Conductor-899664036");
        _itemSearch_bodyRequestVal1.setDirector("Director892408241");
        _itemSearch_bodyRequestVal1.setItemPage(new java.math.BigInteger("-84439421895524469342728289827677535089"));
        _itemSearch_bodyRequestVal1.setKeywords("Keywords382047455");
        _itemSearch_bodyRequestVal1.setManufacturer("Manufacturer37198815");
        _itemSearch_bodyRequestVal1.setMaximumPrice(new java.math.BigInteger("-5440324657018710445841391644491036208"));
        _itemSearch_bodyRequestVal1.setMerchantId("MerchantId-978801618");
        _itemSearch_bodyRequestVal1.setMinimumPrice(new java.math.BigInteger("-78741143259415728028980214709568046244"));
        _itemSearch_bodyRequestVal1.setMinPercentageOff(new java.math.BigInteger("1103582738518720318277317487513838121"));
        _itemSearch_bodyRequestVal1.setMusicLabel("MusicLabel1766300688");
        _itemSearch_bodyRequestVal1.setOrchestra("Orchestra-887956566");
        _itemSearch_bodyRequestVal1.setPower("Power-129740299");
        _itemSearch_bodyRequestVal1.setPublisher("Publisher647135707");
        _itemSearch_bodyRequestVal1.setRelatedItemPage("RelatedItemPage-141581449");
        java.util.List<java.lang.String> _itemSearch_bodyRequestVal1RelationshipType = new java.util.ArrayList<java.lang.String>();
        _itemSearch_bodyRequestVal1.getRelationshipType().addAll(_itemSearch_bodyRequestVal1RelationshipType);
        java.util.List<java.lang.String> _itemSearch_bodyRequestVal1ResponseGroup = new java.util.ArrayList<java.lang.String>();
        _itemSearch_bodyRequestVal1.getResponseGroup().addAll(_itemSearch_bodyRequestVal1ResponseGroup);
        _itemSearch_bodyRequestVal1.setSearchIndex("SearchIndex-885055035");
        _itemSearch_bodyRequestVal1.setSort("Sort-1968523515");
        _itemSearch_bodyRequestVal1.setTitle("Title1992566352");
        _itemSearch_bodyRequestVal1.setReleaseDate("ReleaseDate-1841933715");
        _itemSearch_bodyRequestVal1.setIncludeReviewsSummary("IncludeReviewsSummary10706600");
        _itemSearch_bodyRequestVal1.setTruncateReviewsAt(new java.math.BigInteger("70630076918573258342678304107650549897"));
        _itemSearch_bodyRequest.add(_itemSearch_bodyRequestVal1);
        _itemSearch_body.getRequest().addAll(_itemSearch_bodyRequest);
        com.amazon.webservices.awsecommerceservice.ItemSearchResponse _itemSearch__return = port.itemSearch(_itemSearch_body);
        System.out.println("itemSearch.result=" + _itemSearch__return);


        }
        {
        System.out.println("Invoking cartClear...");
        com.amazon.webservices.awsecommerceservice.CartClear _cartClear_body = new com.amazon.webservices.awsecommerceservice.CartClear();
        _cartClear_body.setMarketplaceDomain("MarketplaceDomain-1336444078");
        _cartClear_body.setAWSAccessKeyId("AWSAccessKeyId402061044");
        _cartClear_body.setAssociateTag("AssociateTag181220046");
        _cartClear_body.setValidate("Validate-444150720");
        _cartClear_body.setXMLEscaping("XMLEscaping1236181680");
        com.amazon.webservices.awsecommerceservice.CartClearRequest _cartClear_bodyShared = new com.amazon.webservices.awsecommerceservice.CartClearRequest();
        _cartClear_bodyShared.setCartId("CartId422314800");
        _cartClear_bodyShared.setHMAC("HMAC1778369891");
        _cartClear_bodyShared.setMergeCart("MergeCart-1007653113");
        java.util.List<java.lang.String> _cartClear_bodySharedResponseGroup = new java.util.ArrayList<java.lang.String>();
        java.lang.String _cartClear_bodySharedResponseGroupVal1 = "_cartClear_bodySharedResponseGroupVal-2102737846";
        _cartClear_bodySharedResponseGroup.add(_cartClear_bodySharedResponseGroupVal1);
        _cartClear_bodyShared.getResponseGroup().addAll(_cartClear_bodySharedResponseGroup);
        _cartClear_body.setShared(_cartClear_bodyShared);
        java.util.List<com.amazon.webservices.awsecommerceservice.CartClearRequest> _cartClear_bodyRequest = new java.util.ArrayList<com.amazon.webservices.awsecommerceservice.CartClearRequest>();
        com.amazon.webservices.awsecommerceservice.CartClearRequest _cartClear_bodyRequestVal1 = new com.amazon.webservices.awsecommerceservice.CartClearRequest();
        _cartClear_bodyRequestVal1.setCartId("CartId-288308093");
        _cartClear_bodyRequestVal1.setHMAC("HMAC-1110700095");
        _cartClear_bodyRequestVal1.setMergeCart("MergeCart-807106431");
        java.util.List<java.lang.String> _cartClear_bodyRequestVal1ResponseGroup = new java.util.ArrayList<java.lang.String>();
        _cartClear_bodyRequestVal1.getResponseGroup().addAll(_cartClear_bodyRequestVal1ResponseGroup);
        _cartClear_bodyRequest.add(_cartClear_bodyRequestVal1);
        _cartClear_body.getRequest().addAll(_cartClear_bodyRequest);
        com.amazon.webservices.awsecommerceservice.CartClearResponse _cartClear__return = port.cartClear(_cartClear_body);
        System.out.println("cartClear.result=" + _cartClear__return);


        }

        System.exit(0);
    }

}
