
package com.amazon.webservices.awsecommerceservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.1.16
 * 2018-10-05T17:30:35.239+05:30
 * Generated source version: 3.1.16
 * 
 */
public final class AWSECommerceServicePortType_AWSECommerceServicePortCN_Client {

    private static final QName SERVICE_NAME = new QName("http://webservices.amazon.com/AWSECommerceService/2011-08-01", "AWSECommerceService");

    private AWSECommerceServicePortType_AWSECommerceServicePortCN_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = AWSECommerceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        AWSECommerceService ss = new AWSECommerceService(wsdlURL, SERVICE_NAME);
        AWSECommerceServicePortType port = ss.getAWSECommerceServicePortCN();  
        
        {
        System.out.println("Invoking cartCreate...");
        com.amazon.webservices.awsecommerceservice.CartCreate _cartCreate_body = new com.amazon.webservices.awsecommerceservice.CartCreate();
        _cartCreate_body.setMarketplaceDomain("MarketplaceDomain505557992");
        _cartCreate_body.setAWSAccessKeyId("AWSAccessKeyId-1060468558");
        _cartCreate_body.setAssociateTag("AssociateTag497852418");
        _cartCreate_body.setValidate("Validate-1858148160");
        _cartCreate_body.setXMLEscaping("XMLEscaping-2058821067");
        com.amazon.webservices.awsecommerceservice.CartCreateRequest _cartCreate_bodyShared = new com.amazon.webservices.awsecommerceservice.CartCreateRequest();
        _cartCreate_bodyShared.setMergeCart("MergeCart316250415");
        com.amazon.webservices.awsecommerceservice.CartCreateRequest.Items _cartCreate_bodySharedItems = new com.amazon.webservices.awsecommerceservice.CartCreateRequest.Items();
        java.util.List<com.amazon.webservices.awsecommerceservice.CartCreateRequest.Items.Item> _cartCreate_bodySharedItemsItem = new java.util.ArrayList<com.amazon.webservices.awsecommerceservice.CartCreateRequest.Items.Item>();
        _cartCreate_bodySharedItems.getItem().addAll(_cartCreate_bodySharedItemsItem);
        _cartCreate_bodyShared.setItems(_cartCreate_bodySharedItems);
        java.util.List<java.lang.String> _cartCreate_bodySharedResponseGroup = new java.util.ArrayList<java.lang.String>();
        java.lang.String _cartCreate_bodySharedResponseGroupVal1 = "_cartCreate_bodySharedResponseGroupVal1330916660";
        _cartCreate_bodySharedResponseGroup.add(_cartCreate_bodySharedResponseGroupVal1);
        _cartCreate_bodyShared.getResponseGroup().addAll(_cartCreate_bodySharedResponseGroup);
        _cartCreate_body.setShared(_cartCreate_bodyShared);
        java.util.List<com.amazon.webservices.awsecommerceservice.CartCreateRequest> _cartCreate_bodyRequest = new java.util.ArrayList<com.amazon.webservices.awsecommerceservice.CartCreateRequest>();
        com.amazon.webservices.awsecommerceservice.CartCreateRequest _cartCreate_bodyRequestVal1 = new com.amazon.webservices.awsecommerceservice.CartCreateRequest();
        _cartCreate_bodyRequestVal1.setMergeCart("MergeCart-733320027");
        com.amazon.webservices.awsecommerceservice.CartCreateRequest.Items _cartCreate_bodyRequestVal1Items = new com.amazon.webservices.awsecommerceservice.CartCreateRequest.Items();
        java.util.List<com.amazon.webservices.awsecommerceservice.CartCreateRequest.Items.Item> _cartCreate_bodyRequestVal1ItemsItem = new java.util.ArrayList<com.amazon.webservices.awsecommerceservice.CartCreateRequest.Items.Item>();
        _cartCreate_bodyRequestVal1Items.getItem().addAll(_cartCreate_bodyRequestVal1ItemsItem);
        _cartCreate_bodyRequestVal1.setItems(_cartCreate_bodyRequestVal1Items);
        java.util.List<java.lang.String> _cartCreate_bodyRequestVal1ResponseGroup = new java.util.ArrayList<java.lang.String>();
        _cartCreate_bodyRequestVal1.getResponseGroup().addAll(_cartCreate_bodyRequestVal1ResponseGroup);
        _cartCreate_bodyRequest.add(_cartCreate_bodyRequestVal1);
        _cartCreate_body.getRequest().addAll(_cartCreate_bodyRequest);
        com.amazon.webservices.awsecommerceservice.CartCreateResponse _cartCreate__return = port.cartCreate(_cartCreate_body);
        System.out.println("cartCreate.result=" + _cartCreate__return);


        }
        {
        System.out.println("Invoking browseNodeLookup...");
        com.amazon.webservices.awsecommerceservice.BrowseNodeLookup _browseNodeLookup_body = new com.amazon.webservices.awsecommerceservice.BrowseNodeLookup();
        _browseNodeLookup_body.setMarketplaceDomain("MarketplaceDomain-353340019");
        _browseNodeLookup_body.setAWSAccessKeyId("AWSAccessKeyId168214751");
        _browseNodeLookup_body.setAssociateTag("AssociateTag-1883156541");
        _browseNodeLookup_body.setValidate("Validate1347310920");
        _browseNodeLookup_body.setXMLEscaping("XMLEscaping-2110001399");
        com.amazon.webservices.awsecommerceservice.BrowseNodeLookupRequest _browseNodeLookup_bodyShared = new com.amazon.webservices.awsecommerceservice.BrowseNodeLookupRequest();
        java.util.List<java.lang.String> _browseNodeLookup_bodySharedBrowseNodeId = new java.util.ArrayList<java.lang.String>();
        java.lang.String _browseNodeLookup_bodySharedBrowseNodeIdVal1 = "_browseNodeLookup_bodySharedBrowseNodeIdVal960841170";
        _browseNodeLookup_bodySharedBrowseNodeId.add(_browseNodeLookup_bodySharedBrowseNodeIdVal1);
        _browseNodeLookup_bodyShared.getBrowseNodeId().addAll(_browseNodeLookup_bodySharedBrowseNodeId);
        java.util.List<java.lang.String> _browseNodeLookup_bodySharedResponseGroup = new java.util.ArrayList<java.lang.String>();
        java.lang.String _browseNodeLookup_bodySharedResponseGroupVal1 = "_browseNodeLookup_bodySharedResponseGroupVal91617705";
        _browseNodeLookup_bodySharedResponseGroup.add(_browseNodeLookup_bodySharedResponseGroupVal1);
        _browseNodeLookup_bodyShared.getResponseGroup().addAll(_browseNodeLookup_bodySharedResponseGroup);
        _browseNodeLookup_body.setShared(_browseNodeLookup_bodyShared);
        java.util.List<com.amazon.webservices.awsecommerceservice.BrowseNodeLookupRequest> _browseNodeLookup_bodyRequest = new java.util.ArrayList<com.amazon.webservices.awsecommerceservice.BrowseNodeLookupRequest>();
        com.amazon.webservices.awsecommerceservice.BrowseNodeLookupRequest _browseNodeLookup_bodyRequestVal1 = new com.amazon.webservices.awsecommerceservice.BrowseNodeLookupRequest();
        java.util.List<java.lang.String> _browseNodeLookup_bodyRequestVal1BrowseNodeId = new java.util.ArrayList<java.lang.String>();
        _browseNodeLookup_bodyRequestVal1.getBrowseNodeId().addAll(_browseNodeLookup_bodyRequestVal1BrowseNodeId);
        java.util.List<java.lang.String> _browseNodeLookup_bodyRequestVal1ResponseGroup = new java.util.ArrayList<java.lang.String>();
        _browseNodeLookup_bodyRequestVal1.getResponseGroup().addAll(_browseNodeLookup_bodyRequestVal1ResponseGroup);
        _browseNodeLookup_bodyRequest.add(_browseNodeLookup_bodyRequestVal1);
        _browseNodeLookup_body.getRequest().addAll(_browseNodeLookup_bodyRequest);
        com.amazon.webservices.awsecommerceservice.BrowseNodeLookupResponse _browseNodeLookup__return = port.browseNodeLookup(_browseNodeLookup_body);
        System.out.println("browseNodeLookup.result=" + _browseNodeLookup__return);


        }
        {
        System.out.println("Invoking cartGet...");
        com.amazon.webservices.awsecommerceservice.CartGet _cartGet_body = new com.amazon.webservices.awsecommerceservice.CartGet();
        _cartGet_body.setMarketplaceDomain("MarketplaceDomain-1350275463");
        _cartGet_body.setAWSAccessKeyId("AWSAccessKeyId791855974");
        _cartGet_body.setAssociateTag("AssociateTag816928280");
        _cartGet_body.setValidate("Validate2003037012");
        _cartGet_body.setXMLEscaping("XMLEscaping-1596603533");
        com.amazon.webservices.awsecommerceservice.CartGetRequest _cartGet_bodyShared = new com.amazon.webservices.awsecommerceservice.CartGetRequest();
        _cartGet_bodyShared.setCartId("CartId-557798920");
        _cartGet_bodyShared.setHMAC("HMAC710565288");
        _cartGet_bodyShared.setMergeCart("MergeCart-1905386054");
        java.util.List<java.lang.String> _cartGet_bodySharedResponseGroup = new java.util.ArrayList<java.lang.String>();
        java.lang.String _cartGet_bodySharedResponseGroupVal1 = "_cartGet_bodySharedResponseGroupVal598917473";
        _cartGet_bodySharedResponseGroup.add(_cartGet_bodySharedResponseGroupVal1);
        _cartGet_bodyShared.getResponseGroup().addAll(_cartGet_bodySharedResponseGroup);
        _cartGet_body.setShared(_cartGet_bodyShared);
        java.util.List<com.amazon.webservices.awsecommerceservice.CartGetRequest> _cartGet_bodyRequest = new java.util.ArrayList<com.amazon.webservices.awsecommerceservice.CartGetRequest>();
        com.amazon.webservices.awsecommerceservice.CartGetRequest _cartGet_bodyRequestVal1 = new com.amazon.webservices.awsecommerceservice.CartGetRequest();
        _cartGet_bodyRequestVal1.setCartId("CartId1248782047");
        _cartGet_bodyRequestVal1.setHMAC("HMAC1489131138");
        _cartGet_bodyRequestVal1.setMergeCart("MergeCart-1127335505");
        java.util.List<java.lang.String> _cartGet_bodyRequestVal1ResponseGroup = new java.util.ArrayList<java.lang.String>();
        _cartGet_bodyRequestVal1.getResponseGroup().addAll(_cartGet_bodyRequestVal1ResponseGroup);
        _cartGet_bodyRequest.add(_cartGet_bodyRequestVal1);
        _cartGet_body.getRequest().addAll(_cartGet_bodyRequest);
        com.amazon.webservices.awsecommerceservice.CartGetResponse _cartGet__return = port.cartGet(_cartGet_body);
        System.out.println("cartGet.result=" + _cartGet__return);


        }
        {
        System.out.println("Invoking cartModify...");
        com.amazon.webservices.awsecommerceservice.CartModify _cartModify_body = new com.amazon.webservices.awsecommerceservice.CartModify();
        _cartModify_body.setMarketplaceDomain("MarketplaceDomain283934244");
        _cartModify_body.setAWSAccessKeyId("AWSAccessKeyId-1490320265");
        _cartModify_body.setAssociateTag("AssociateTag-566266088");
        _cartModify_body.setValidate("Validate-779505542");
        _cartModify_body.setXMLEscaping("XMLEscaping404039507");
        com.amazon.webservices.awsecommerceservice.CartModifyRequest _cartModify_bodyShared = new com.amazon.webservices.awsecommerceservice.CartModifyRequest();
        _cartModify_bodyShared.setCartId("CartId-87674860");
        _cartModify_bodyShared.setHMAC("HMAC-278928662");
        _cartModify_bodyShared.setMergeCart("MergeCart1019693477");
        com.amazon.webservices.awsecommerceservice.CartModifyRequest.Items _cartModify_bodySharedItems = new com.amazon.webservices.awsecommerceservice.CartModifyRequest.Items();
        java.util.List<com.amazon.webservices.awsecommerceservice.CartModifyRequest.Items.Item> _cartModify_bodySharedItemsItem = new java.util.ArrayList<com.amazon.webservices.awsecommerceservice.CartModifyRequest.Items.Item>();
        _cartModify_bodySharedItems.getItem().addAll(_cartModify_bodySharedItemsItem);
        _cartModify_bodyShared.setItems(_cartModify_bodySharedItems);
        java.util.List<java.lang.String> _cartModify_bodySharedResponseGroup = new java.util.ArrayList<java.lang.String>();
        java.lang.String _cartModify_bodySharedResponseGroupVal1 = "_cartModify_bodySharedResponseGroupVal1288297859";
        _cartModify_bodySharedResponseGroup.add(_cartModify_bodySharedResponseGroupVal1);
        _cartModify_bodyShared.getResponseGroup().addAll(_cartModify_bodySharedResponseGroup);
        _cartModify_body.setShared(_cartModify_bodyShared);
        java.util.List<com.amazon.webservices.awsecommerceservice.CartModifyRequest> _cartModify_bodyRequest = new java.util.ArrayList<com.amazon.webservices.awsecommerceservice.CartModifyRequest>();
        com.amazon.webservices.awsecommerceservice.CartModifyRequest _cartModify_bodyRequestVal1 = new com.amazon.webservices.awsecommerceservice.CartModifyRequest();
        _cartModify_bodyRequestVal1.setCartId("CartId-1173246481");
        _cartModify_bodyRequestVal1.setHMAC("HMAC-1304084113");
        _cartModify_bodyRequestVal1.setMergeCart("MergeCart1167014420");
        com.amazon.webservices.awsecommerceservice.CartModifyRequest.Items _cartModify_bodyRequestVal1Items = new com.amazon.webservices.awsecommerceservice.CartModifyRequest.Items();
        java.util.List<com.amazon.webservices.awsecommerceservice.CartModifyRequest.Items.Item> _cartModify_bodyRequestVal1ItemsItem = new java.util.ArrayList<com.amazon.webservices.awsecommerceservice.CartModifyRequest.Items.Item>();
        _cartModify_bodyRequestVal1Items.getItem().addAll(_cartModify_bodyRequestVal1ItemsItem);
        _cartModify_bodyRequestVal1.setItems(_cartModify_bodyRequestVal1Items);
        java.util.List<java.lang.String> _cartModify_bodyRequestVal1ResponseGroup = new java.util.ArrayList<java.lang.String>();
        _cartModify_bodyRequestVal1.getResponseGroup().addAll(_cartModify_bodyRequestVal1ResponseGroup);
        _cartModify_bodyRequest.add(_cartModify_bodyRequestVal1);
        _cartModify_body.getRequest().addAll(_cartModify_bodyRequest);
        com.amazon.webservices.awsecommerceservice.CartModifyResponse _cartModify__return = port.cartModify(_cartModify_body);
        System.out.println("cartModify.result=" + _cartModify__return);


        }
        {
        System.out.println("Invoking cartAdd...");
        com.amazon.webservices.awsecommerceservice.CartAdd _cartAdd_body = new com.amazon.webservices.awsecommerceservice.CartAdd();
        _cartAdd_body.setMarketplaceDomain("MarketplaceDomain1017675719");
        _cartAdd_body.setAWSAccessKeyId("AWSAccessKeyId219420762");
        _cartAdd_body.setAssociateTag("AssociateTag-68657349");
        _cartAdd_body.setValidate("Validate663558232");
        _cartAdd_body.setXMLEscaping("XMLEscaping-237491334");
        com.amazon.webservices.awsecommerceservice.CartAddRequest _cartAdd_bodyShared = new com.amazon.webservices.awsecommerceservice.CartAddRequest();
        _cartAdd_bodyShared.setCartId("CartId1184849467");
        _cartAdd_bodyShared.setHMAC("HMAC1754479965");
        _cartAdd_bodyShared.setMergeCart("MergeCart286016068");
        com.amazon.webservices.awsecommerceservice.CartAddRequest.Items _cartAdd_bodySharedItems = new com.amazon.webservices.awsecommerceservice.CartAddRequest.Items();
        java.util.List<com.amazon.webservices.awsecommerceservice.CartAddRequest.Items.Item> _cartAdd_bodySharedItemsItem = new java.util.ArrayList<com.amazon.webservices.awsecommerceservice.CartAddRequest.Items.Item>();
        _cartAdd_bodySharedItems.getItem().addAll(_cartAdd_bodySharedItemsItem);
        _cartAdd_bodyShared.setItems(_cartAdd_bodySharedItems);
        java.util.List<java.lang.String> _cartAdd_bodySharedResponseGroup = new java.util.ArrayList<java.lang.String>();
        java.lang.String _cartAdd_bodySharedResponseGroupVal1 = "_cartAdd_bodySharedResponseGroupVal-684493765";
        _cartAdd_bodySharedResponseGroup.add(_cartAdd_bodySharedResponseGroupVal1);
        _cartAdd_bodyShared.getResponseGroup().addAll(_cartAdd_bodySharedResponseGroup);
        _cartAdd_body.setShared(_cartAdd_bodyShared);
        java.util.List<com.amazon.webservices.awsecommerceservice.CartAddRequest> _cartAdd_bodyRequest = new java.util.ArrayList<com.amazon.webservices.awsecommerceservice.CartAddRequest>();
        com.amazon.webservices.awsecommerceservice.CartAddRequest _cartAdd_bodyRequestVal1 = new com.amazon.webservices.awsecommerceservice.CartAddRequest();
        _cartAdd_bodyRequestVal1.setCartId("CartId340702391");
        _cartAdd_bodyRequestVal1.setHMAC("HMAC1759654665");
        _cartAdd_bodyRequestVal1.setMergeCart("MergeCart-337868863");
        com.amazon.webservices.awsecommerceservice.CartAddRequest.Items _cartAdd_bodyRequestVal1Items = new com.amazon.webservices.awsecommerceservice.CartAddRequest.Items();
        java.util.List<com.amazon.webservices.awsecommerceservice.CartAddRequest.Items.Item> _cartAdd_bodyRequestVal1ItemsItem = new java.util.ArrayList<com.amazon.webservices.awsecommerceservice.CartAddRequest.Items.Item>();
        _cartAdd_bodyRequestVal1Items.getItem().addAll(_cartAdd_bodyRequestVal1ItemsItem);
        _cartAdd_bodyRequestVal1.setItems(_cartAdd_bodyRequestVal1Items);
        java.util.List<java.lang.String> _cartAdd_bodyRequestVal1ResponseGroup = new java.util.ArrayList<java.lang.String>();
        _cartAdd_bodyRequestVal1.getResponseGroup().addAll(_cartAdd_bodyRequestVal1ResponseGroup);
        _cartAdd_bodyRequest.add(_cartAdd_bodyRequestVal1);
        _cartAdd_body.getRequest().addAll(_cartAdd_bodyRequest);
        com.amazon.webservices.awsecommerceservice.CartAddResponse _cartAdd__return = port.cartAdd(_cartAdd_body);
        System.out.println("cartAdd.result=" + _cartAdd__return);


        }
        {
        System.out.println("Invoking itemLookup...");
        com.amazon.webservices.awsecommerceservice.ItemLookup _itemLookup_body = new com.amazon.webservices.awsecommerceservice.ItemLookup();
        _itemLookup_body.setMarketplaceDomain("MarketplaceDomain110073912");
        _itemLookup_body.setAWSAccessKeyId("AWSAccessKeyId-226693075");
        _itemLookup_body.setAssociateTag("AssociateTag-1904016010");
        _itemLookup_body.setValidate("Validate2018914014");
        _itemLookup_body.setXMLEscaping("XMLEscaping2139894959");
        com.amazon.webservices.awsecommerceservice.ItemLookupRequest _itemLookup_bodyShared = new com.amazon.webservices.awsecommerceservice.ItemLookupRequest();
        _itemLookup_bodyShared.setCondition("Condition9631845");
        _itemLookup_bodyShared.setIdType("IdType-1510794743");
        _itemLookup_bodyShared.setMerchantId("MerchantId-1785617109");
        java.util.List<java.lang.String> _itemLookup_bodySharedItemId = new java.util.ArrayList<java.lang.String>();
        java.lang.String _itemLookup_bodySharedItemIdVal1 = "_itemLookup_bodySharedItemIdVal1108033202";
        _itemLookup_bodySharedItemId.add(_itemLookup_bodySharedItemIdVal1);
        _itemLookup_bodyShared.getItemId().addAll(_itemLookup_bodySharedItemId);
        java.util.List<java.lang.String> _itemLookup_bodySharedResponseGroup = new java.util.ArrayList<java.lang.String>();
        java.lang.String _itemLookup_bodySharedResponseGroupVal1 = "_itemLookup_bodySharedResponseGroupVal1548536841";
        _itemLookup_bodySharedResponseGroup.add(_itemLookup_bodySharedResponseGroupVal1);
        _itemLookup_bodyShared.getResponseGroup().addAll(_itemLookup_bodySharedResponseGroup);
        _itemLookup_bodyShared.setSearchIndex("SearchIndex1525425843");
        _itemLookup_bodyShared.setVariationPage("VariationPage1045983814");
        _itemLookup_bodyShared.setRelatedItemPage("RelatedItemPage1932084266");
        java.util.List<java.lang.String> _itemLookup_bodySharedRelationshipType = new java.util.ArrayList<java.lang.String>();
        java.lang.String _itemLookup_bodySharedRelationshipTypeVal1 = "_itemLookup_bodySharedRelationshipTypeVal1367787347";
        _itemLookup_bodySharedRelationshipType.add(_itemLookup_bodySharedRelationshipTypeVal1);
        _itemLookup_bodyShared.getRelationshipType().addAll(_itemLookup_bodySharedRelationshipType);
        _itemLookup_bodyShared.setIncludeReviewsSummary("IncludeReviewsSummary1178666134");
        _itemLookup_bodyShared.setTruncateReviewsAt(new java.math.BigInteger("43668728395141102378715553764403934994"));
        _itemLookup_body.setShared(_itemLookup_bodyShared);
        java.util.List<com.amazon.webservices.awsecommerceservice.ItemLookupRequest> _itemLookup_bodyRequest = new java.util.ArrayList<com.amazon.webservices.awsecommerceservice.ItemLookupRequest>();
        com.amazon.webservices.awsecommerceservice.ItemLookupRequest _itemLookup_bodyRequestVal1 = new com.amazon.webservices.awsecommerceservice.ItemLookupRequest();
        _itemLookup_bodyRequestVal1.setCondition("Condition1720322551");
        _itemLookup_bodyRequestVal1.setIdType("IdType1481594163");
        _itemLookup_bodyRequestVal1.setMerchantId("MerchantId-1426401116");
        java.util.List<java.lang.String> _itemLookup_bodyRequestVal1ItemId = new java.util.ArrayList<java.lang.String>();
        _itemLookup_bodyRequestVal1.getItemId().addAll(_itemLookup_bodyRequestVal1ItemId);
        java.util.List<java.lang.String> _itemLookup_bodyRequestVal1ResponseGroup = new java.util.ArrayList<java.lang.String>();
        _itemLookup_bodyRequestVal1.getResponseGroup().addAll(_itemLookup_bodyRequestVal1ResponseGroup);
        _itemLookup_bodyRequestVal1.setSearchIndex("SearchIndex-1998682066");
        _itemLookup_bodyRequestVal1.setVariationPage("VariationPage1043648213");
        _itemLookup_bodyRequestVal1.setRelatedItemPage("RelatedItemPage-2041657995");
        java.util.List<java.lang.String> _itemLookup_bodyRequestVal1RelationshipType = new java.util.ArrayList<java.lang.String>();
        _itemLookup_bodyRequestVal1.getRelationshipType().addAll(_itemLookup_bodyRequestVal1RelationshipType);
        _itemLookup_bodyRequestVal1.setIncludeReviewsSummary("IncludeReviewsSummary971011285");
        _itemLookup_bodyRequestVal1.setTruncateReviewsAt(new java.math.BigInteger("-4567201845249113634714765610514802989"));
        _itemLookup_bodyRequest.add(_itemLookup_bodyRequestVal1);
        _itemLookup_body.getRequest().addAll(_itemLookup_bodyRequest);
        com.amazon.webservices.awsecommerceservice.ItemLookupResponse _itemLookup__return = port.itemLookup(_itemLookup_body);
        System.out.println("itemLookup.result=" + _itemLookup__return);


        }
        {
        System.out.println("Invoking similarityLookup...");
        com.amazon.webservices.awsecommerceservice.SimilarityLookup _similarityLookup_body = new com.amazon.webservices.awsecommerceservice.SimilarityLookup();
        _similarityLookup_body.setMarketplaceDomain("MarketplaceDomain186966003");
        _similarityLookup_body.setAWSAccessKeyId("AWSAccessKeyId2142611664");
        _similarityLookup_body.setAssociateTag("AssociateTag378370554");
        _similarityLookup_body.setValidate("Validate-2028211180");
        _similarityLookup_body.setXMLEscaping("XMLEscaping-1965237944");
        com.amazon.webservices.awsecommerceservice.SimilarityLookupRequest _similarityLookup_bodyShared = new com.amazon.webservices.awsecommerceservice.SimilarityLookupRequest();
        _similarityLookup_bodyShared.setCondition("Condition-134935942");
        java.util.List<java.lang.String> _similarityLookup_bodySharedItemId = new java.util.ArrayList<java.lang.String>();
        java.lang.String _similarityLookup_bodySharedItemIdVal1 = "_similarityLookup_bodySharedItemIdVal-2122395989";
        _similarityLookup_bodySharedItemId.add(_similarityLookup_bodySharedItemIdVal1);
        _similarityLookup_bodyShared.getItemId().addAll(_similarityLookup_bodySharedItemId);
        _similarityLookup_bodyShared.setMerchantId("MerchantId328646139");
        java.util.List<java.lang.String> _similarityLookup_bodySharedResponseGroup = new java.util.ArrayList<java.lang.String>();
        java.lang.String _similarityLookup_bodySharedResponseGroupVal1 = "_similarityLookup_bodySharedResponseGroupVal1058897195";
        _similarityLookup_bodySharedResponseGroup.add(_similarityLookup_bodySharedResponseGroupVal1);
        _similarityLookup_bodyShared.getResponseGroup().addAll(_similarityLookup_bodySharedResponseGroup);
        _similarityLookup_bodyShared.setSimilarityType("SimilarityType-414414525");
        _similarityLookup_body.setShared(_similarityLookup_bodyShared);
        java.util.List<com.amazon.webservices.awsecommerceservice.SimilarityLookupRequest> _similarityLookup_bodyRequest = new java.util.ArrayList<com.amazon.webservices.awsecommerceservice.SimilarityLookupRequest>();
        com.amazon.webservices.awsecommerceservice.SimilarityLookupRequest _similarityLookup_bodyRequestVal1 = new com.amazon.webservices.awsecommerceservice.SimilarityLookupRequest();
        _similarityLookup_bodyRequestVal1.setCondition("Condition-1738634834");
        java.util.List<java.lang.String> _similarityLookup_bodyRequestVal1ItemId = new java.util.ArrayList<java.lang.String>();
        _similarityLookup_bodyRequestVal1.getItemId().addAll(_similarityLookup_bodyRequestVal1ItemId);
        _similarityLookup_bodyRequestVal1.setMerchantId("MerchantId2088937174");
        java.util.List<java.lang.String> _similarityLookup_bodyRequestVal1ResponseGroup = new java.util.ArrayList<java.lang.String>();
        _similarityLookup_bodyRequestVal1.getResponseGroup().addAll(_similarityLookup_bodyRequestVal1ResponseGroup);
        _similarityLookup_bodyRequestVal1.setSimilarityType("SimilarityType1947462162");
        _similarityLookup_bodyRequest.add(_similarityLookup_bodyRequestVal1);
        _similarityLookup_body.getRequest().addAll(_similarityLookup_bodyRequest);
        com.amazon.webservices.awsecommerceservice.SimilarityLookupResponse _similarityLookup__return = port.similarityLookup(_similarityLookup_body);
        System.out.println("similarityLookup.result=" + _similarityLookup__return);


        }
        {
        System.out.println("Invoking itemSearch...");
        com.amazon.webservices.awsecommerceservice.ItemSearch _itemSearch_body = new com.amazon.webservices.awsecommerceservice.ItemSearch();
        _itemSearch_body.setMarketplaceDomain("MarketplaceDomain1566963748");
        _itemSearch_body.setAWSAccessKeyId("AWSAccessKeyId1785997887");
        _itemSearch_body.setAssociateTag("AssociateTag-361990453");
        _itemSearch_body.setXMLEscaping("XMLEscaping-1570953279");
        _itemSearch_body.setValidate("Validate-1937479779");
        com.amazon.webservices.awsecommerceservice.ItemSearchRequest _itemSearch_bodyShared = new com.amazon.webservices.awsecommerceservice.ItemSearchRequest();
        _itemSearch_bodyShared.setActor("Actor-203220776");
        _itemSearch_bodyShared.setArtist("Artist1981441575");
        _itemSearch_bodyShared.setAvailability("Availability-746765772");
        java.util.List<java.lang.String> _itemSearch_bodySharedAudienceRating = new java.util.ArrayList<java.lang.String>();
        java.lang.String _itemSearch_bodySharedAudienceRatingVal1 = "_itemSearch_bodySharedAudienceRatingVal345206981";
        _itemSearch_bodySharedAudienceRating.add(_itemSearch_bodySharedAudienceRatingVal1);
        _itemSearch_bodyShared.getAudienceRating().addAll(_itemSearch_bodySharedAudienceRating);
        _itemSearch_bodyShared.setAuthor("Author1594988207");
        _itemSearch_bodyShared.setBrand("Brand-1035947887");
        _itemSearch_bodyShared.setBrowseNode("BrowseNode468889281");
        _itemSearch_bodyShared.setComposer("Composer-545808990");
        _itemSearch_bodyShared.setCondition("Condition370188675");
        _itemSearch_bodyShared.setConductor("Conductor-1408260223");
        _itemSearch_bodyShared.setDirector("Director121134974");
        _itemSearch_bodyShared.setItemPage(new java.math.BigInteger("-78147275191982613523068086100853839649"));
        _itemSearch_bodyShared.setKeywords("Keywords720526826");
        _itemSearch_bodyShared.setManufacturer("Manufacturer-1915459584");
        _itemSearch_bodyShared.setMaximumPrice(new java.math.BigInteger("65913251843358959716478904749877150949"));
        _itemSearch_bodyShared.setMerchantId("MerchantId2049510345");
        _itemSearch_bodyShared.setMinimumPrice(new java.math.BigInteger("-89222587457241430092990670941849387913"));
        _itemSearch_bodyShared.setMinPercentageOff(new java.math.BigInteger("-37905369322951339563236620989881290843"));
        _itemSearch_bodyShared.setMusicLabel("MusicLabel305212017");
        _itemSearch_bodyShared.setOrchestra("Orchestra646675139");
        _itemSearch_bodyShared.setPower("Power-306717190");
        _itemSearch_bodyShared.setPublisher("Publisher-204237323");
        _itemSearch_bodyShared.setRelatedItemPage("RelatedItemPage-1490738232");
        java.util.List<java.lang.String> _itemSearch_bodySharedRelationshipType = new java.util.ArrayList<java.lang.String>();
        java.lang.String _itemSearch_bodySharedRelationshipTypeVal1 = "_itemSearch_bodySharedRelationshipTypeVal1069176423";
        _itemSearch_bodySharedRelationshipType.add(_itemSearch_bodySharedRelationshipTypeVal1);
        _itemSearch_bodyShared.getRelationshipType().addAll(_itemSearch_bodySharedRelationshipType);
        java.util.List<java.lang.String> _itemSearch_bodySharedResponseGroup = new java.util.ArrayList<java.lang.String>();
        java.lang.String _itemSearch_bodySharedResponseGroupVal1 = "_itemSearch_bodySharedResponseGroupVal-444435963";
        _itemSearch_bodySharedResponseGroup.add(_itemSearch_bodySharedResponseGroupVal1);
        _itemSearch_bodyShared.getResponseGroup().addAll(_itemSearch_bodySharedResponseGroup);
        _itemSearch_bodyShared.setSearchIndex("SearchIndex1964101194");
        _itemSearch_bodyShared.setSort("Sort810314236");
        _itemSearch_bodyShared.setTitle("Title943850280");
        _itemSearch_bodyShared.setReleaseDate("ReleaseDate-213843477");
        _itemSearch_bodyShared.setIncludeReviewsSummary("IncludeReviewsSummary-836968731");
        _itemSearch_bodyShared.setTruncateReviewsAt(new java.math.BigInteger("21113846334542234616458057675667919828"));
        _itemSearch_body.setShared(_itemSearch_bodyShared);
        java.util.List<com.amazon.webservices.awsecommerceservice.ItemSearchRequest> _itemSearch_bodyRequest = new java.util.ArrayList<com.amazon.webservices.awsecommerceservice.ItemSearchRequest>();
        com.amazon.webservices.awsecommerceservice.ItemSearchRequest _itemSearch_bodyRequestVal1 = new com.amazon.webservices.awsecommerceservice.ItemSearchRequest();
        _itemSearch_bodyRequestVal1.setActor("Actor-1721401899");
        _itemSearch_bodyRequestVal1.setArtist("Artist2006551158");
        _itemSearch_bodyRequestVal1.setAvailability("Availability897754513");
        java.util.List<java.lang.String> _itemSearch_bodyRequestVal1AudienceRating = new java.util.ArrayList<java.lang.String>();
        _itemSearch_bodyRequestVal1.getAudienceRating().addAll(_itemSearch_bodyRequestVal1AudienceRating);
        _itemSearch_bodyRequestVal1.setAuthor("Author-1203130470");
        _itemSearch_bodyRequestVal1.setBrand("Brand255785746");
        _itemSearch_bodyRequestVal1.setBrowseNode("BrowseNode-1452102472");
        _itemSearch_bodyRequestVal1.setComposer("Composer1465625032");
        _itemSearch_bodyRequestVal1.setCondition("Condition603843063");
        _itemSearch_bodyRequestVal1.setConductor("Conductor2030000738");
        _itemSearch_bodyRequestVal1.setDirector("Director-1865588504");
        _itemSearch_bodyRequestVal1.setItemPage(new java.math.BigInteger("22729148979780169693185093602466156620"));
        _itemSearch_bodyRequestVal1.setKeywords("Keywords977389896");
        _itemSearch_bodyRequestVal1.setManufacturer("Manufacturer1274517257");
        _itemSearch_bodyRequestVal1.setMaximumPrice(new java.math.BigInteger("-91216026914926083695630012126999494374"));
        _itemSearch_bodyRequestVal1.setMerchantId("MerchantId1928316979");
        _itemSearch_bodyRequestVal1.setMinimumPrice(new java.math.BigInteger("-37898596064066537005020224999587089178"));
        _itemSearch_bodyRequestVal1.setMinPercentageOff(new java.math.BigInteger("8928335470849027317386896522235405344"));
        _itemSearch_bodyRequestVal1.setMusicLabel("MusicLabel1649014501");
        _itemSearch_bodyRequestVal1.setOrchestra("Orchestra660014754");
        _itemSearch_bodyRequestVal1.setPower("Power346064132");
        _itemSearch_bodyRequestVal1.setPublisher("Publisher-471534884");
        _itemSearch_bodyRequestVal1.setRelatedItemPage("RelatedItemPage338683356");
        java.util.List<java.lang.String> _itemSearch_bodyRequestVal1RelationshipType = new java.util.ArrayList<java.lang.String>();
        _itemSearch_bodyRequestVal1.getRelationshipType().addAll(_itemSearch_bodyRequestVal1RelationshipType);
        java.util.List<java.lang.String> _itemSearch_bodyRequestVal1ResponseGroup = new java.util.ArrayList<java.lang.String>();
        _itemSearch_bodyRequestVal1.getResponseGroup().addAll(_itemSearch_bodyRequestVal1ResponseGroup);
        _itemSearch_bodyRequestVal1.setSearchIndex("SearchIndex-591283721");
        _itemSearch_bodyRequestVal1.setSort("Sort1210517129");
        _itemSearch_bodyRequestVal1.setTitle("Title279117339");
        _itemSearch_bodyRequestVal1.setReleaseDate("ReleaseDate-1228281046");
        _itemSearch_bodyRequestVal1.setIncludeReviewsSummary("IncludeReviewsSummary-1393176966");
        _itemSearch_bodyRequestVal1.setTruncateReviewsAt(new java.math.BigInteger("6104012148859726158631563499153440773"));
        _itemSearch_bodyRequest.add(_itemSearch_bodyRequestVal1);
        _itemSearch_body.getRequest().addAll(_itemSearch_bodyRequest);
        com.amazon.webservices.awsecommerceservice.ItemSearchResponse _itemSearch__return = port.itemSearch(_itemSearch_body);
        System.out.println("itemSearch.result=" + _itemSearch__return);


        }
        {
        System.out.println("Invoking cartClear...");
        com.amazon.webservices.awsecommerceservice.CartClear _cartClear_body = new com.amazon.webservices.awsecommerceservice.CartClear();
        _cartClear_body.setMarketplaceDomain("MarketplaceDomain-1589296835");
        _cartClear_body.setAWSAccessKeyId("AWSAccessKeyId-806083045");
        _cartClear_body.setAssociateTag("AssociateTag47416118");
        _cartClear_body.setValidate("Validate1553418187");
        _cartClear_body.setXMLEscaping("XMLEscaping-509966817");
        com.amazon.webservices.awsecommerceservice.CartClearRequest _cartClear_bodyShared = new com.amazon.webservices.awsecommerceservice.CartClearRequest();
        _cartClear_bodyShared.setCartId("CartId-578520447");
        _cartClear_bodyShared.setHMAC("HMAC455437417");
        _cartClear_bodyShared.setMergeCart("MergeCart2039476632");
        java.util.List<java.lang.String> _cartClear_bodySharedResponseGroup = new java.util.ArrayList<java.lang.String>();
        java.lang.String _cartClear_bodySharedResponseGroupVal1 = "_cartClear_bodySharedResponseGroupVal-1855460546";
        _cartClear_bodySharedResponseGroup.add(_cartClear_bodySharedResponseGroupVal1);
        _cartClear_bodyShared.getResponseGroup().addAll(_cartClear_bodySharedResponseGroup);
        _cartClear_body.setShared(_cartClear_bodyShared);
        java.util.List<com.amazon.webservices.awsecommerceservice.CartClearRequest> _cartClear_bodyRequest = new java.util.ArrayList<com.amazon.webservices.awsecommerceservice.CartClearRequest>();
        com.amazon.webservices.awsecommerceservice.CartClearRequest _cartClear_bodyRequestVal1 = new com.amazon.webservices.awsecommerceservice.CartClearRequest();
        _cartClear_bodyRequestVal1.setCartId("CartId230338044");
        _cartClear_bodyRequestVal1.setHMAC("HMAC-923229755");
        _cartClear_bodyRequestVal1.setMergeCart("MergeCart-68468388");
        java.util.List<java.lang.String> _cartClear_bodyRequestVal1ResponseGroup = new java.util.ArrayList<java.lang.String>();
        _cartClear_bodyRequestVal1.getResponseGroup().addAll(_cartClear_bodyRequestVal1ResponseGroup);
        _cartClear_bodyRequest.add(_cartClear_bodyRequestVal1);
        _cartClear_body.getRequest().addAll(_cartClear_bodyRequest);
        com.amazon.webservices.awsecommerceservice.CartClearResponse _cartClear__return = port.cartClear(_cartClear_body);
        System.out.println("cartClear.result=" + _cartClear__return);


        }

        System.exit(0);
    }

}
