
package com.amazon.webservices.awsecommerceservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.1.16
 * 2018-10-05T17:30:35.250+05:30
 * Generated source version: 3.1.16
 * 
 */
public final class AWSECommerceServicePortType_AWSECommerceServicePortIT_Client {

    private static final QName SERVICE_NAME = new QName("http://webservices.amazon.com/AWSECommerceService/2011-08-01", "AWSECommerceService");

    private AWSECommerceServicePortType_AWSECommerceServicePortIT_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = AWSECommerceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        AWSECommerceService ss = new AWSECommerceService(wsdlURL, SERVICE_NAME);
        AWSECommerceServicePortType port = ss.getAWSECommerceServicePortIT();  
        
        {
        System.out.println("Invoking cartCreate...");
        com.amazon.webservices.awsecommerceservice.CartCreate _cartCreate_body = new com.amazon.webservices.awsecommerceservice.CartCreate();
        _cartCreate_body.setMarketplaceDomain("MarketplaceDomain1792251839");
        _cartCreate_body.setAWSAccessKeyId("AWSAccessKeyId642887304");
        _cartCreate_body.setAssociateTag("AssociateTag-295817220");
        _cartCreate_body.setValidate("Validate1384000745");
        _cartCreate_body.setXMLEscaping("XMLEscaping732578424");
        com.amazon.webservices.awsecommerceservice.CartCreateRequest _cartCreate_bodyShared = new com.amazon.webservices.awsecommerceservice.CartCreateRequest();
        _cartCreate_bodyShared.setMergeCart("MergeCart-820638914");
        com.amazon.webservices.awsecommerceservice.CartCreateRequest.Items _cartCreate_bodySharedItems = new com.amazon.webservices.awsecommerceservice.CartCreateRequest.Items();
        java.util.List<com.amazon.webservices.awsecommerceservice.CartCreateRequest.Items.Item> _cartCreate_bodySharedItemsItem = new java.util.ArrayList<com.amazon.webservices.awsecommerceservice.CartCreateRequest.Items.Item>();
        _cartCreate_bodySharedItems.getItem().addAll(_cartCreate_bodySharedItemsItem);
        _cartCreate_bodyShared.setItems(_cartCreate_bodySharedItems);
        java.util.List<java.lang.String> _cartCreate_bodySharedResponseGroup = new java.util.ArrayList<java.lang.String>();
        java.lang.String _cartCreate_bodySharedResponseGroupVal1 = "_cartCreate_bodySharedResponseGroupVal-1995642077";
        _cartCreate_bodySharedResponseGroup.add(_cartCreate_bodySharedResponseGroupVal1);
        _cartCreate_bodyShared.getResponseGroup().addAll(_cartCreate_bodySharedResponseGroup);
        _cartCreate_body.setShared(_cartCreate_bodyShared);
        java.util.List<com.amazon.webservices.awsecommerceservice.CartCreateRequest> _cartCreate_bodyRequest = new java.util.ArrayList<com.amazon.webservices.awsecommerceservice.CartCreateRequest>();
        com.amazon.webservices.awsecommerceservice.CartCreateRequest _cartCreate_bodyRequestVal1 = new com.amazon.webservices.awsecommerceservice.CartCreateRequest();
        _cartCreate_bodyRequestVal1.setMergeCart("MergeCart100396539");
        com.amazon.webservices.awsecommerceservice.CartCreateRequest.Items _cartCreate_bodyRequestVal1Items = new com.amazon.webservices.awsecommerceservice.CartCreateRequest.Items();
        java.util.List<com.amazon.webservices.awsecommerceservice.CartCreateRequest.Items.Item> _cartCreate_bodyRequestVal1ItemsItem = new java.util.ArrayList<com.amazon.webservices.awsecommerceservice.CartCreateRequest.Items.Item>();
        _cartCreate_bodyRequestVal1Items.getItem().addAll(_cartCreate_bodyRequestVal1ItemsItem);
        _cartCreate_bodyRequestVal1.setItems(_cartCreate_bodyRequestVal1Items);
        java.util.List<java.lang.String> _cartCreate_bodyRequestVal1ResponseGroup = new java.util.ArrayList<java.lang.String>();
        _cartCreate_bodyRequestVal1.getResponseGroup().addAll(_cartCreate_bodyRequestVal1ResponseGroup);
        _cartCreate_bodyRequest.add(_cartCreate_bodyRequestVal1);
        _cartCreate_body.getRequest().addAll(_cartCreate_bodyRequest);
        com.amazon.webservices.awsecommerceservice.CartCreateResponse _cartCreate__return = port.cartCreate(_cartCreate_body);
        System.out.println("cartCreate.result=" + _cartCreate__return);


        }
        {
        System.out.println("Invoking browseNodeLookup...");
        com.amazon.webservices.awsecommerceservice.BrowseNodeLookup _browseNodeLookup_body = new com.amazon.webservices.awsecommerceservice.BrowseNodeLookup();
        _browseNodeLookup_body.setMarketplaceDomain("MarketplaceDomain-2013710943");
        _browseNodeLookup_body.setAWSAccessKeyId("AWSAccessKeyId-1094893571");
        _browseNodeLookup_body.setAssociateTag("AssociateTag724695940");
        _browseNodeLookup_body.setValidate("Validate867725433");
        _browseNodeLookup_body.setXMLEscaping("XMLEscaping-1130866228");
        com.amazon.webservices.awsecommerceservice.BrowseNodeLookupRequest _browseNodeLookup_bodyShared = new com.amazon.webservices.awsecommerceservice.BrowseNodeLookupRequest();
        java.util.List<java.lang.String> _browseNodeLookup_bodySharedBrowseNodeId = new java.util.ArrayList<java.lang.String>();
        java.lang.String _browseNodeLookup_bodySharedBrowseNodeIdVal1 = "_browseNodeLookup_bodySharedBrowseNodeIdVal-697067706";
        _browseNodeLookup_bodySharedBrowseNodeId.add(_browseNodeLookup_bodySharedBrowseNodeIdVal1);
        _browseNodeLookup_bodyShared.getBrowseNodeId().addAll(_browseNodeLookup_bodySharedBrowseNodeId);
        java.util.List<java.lang.String> _browseNodeLookup_bodySharedResponseGroup = new java.util.ArrayList<java.lang.String>();
        java.lang.String _browseNodeLookup_bodySharedResponseGroupVal1 = "_browseNodeLookup_bodySharedResponseGroupVal637330355";
        _browseNodeLookup_bodySharedResponseGroup.add(_browseNodeLookup_bodySharedResponseGroupVal1);
        _browseNodeLookup_bodyShared.getResponseGroup().addAll(_browseNodeLookup_bodySharedResponseGroup);
        _browseNodeLookup_body.setShared(_browseNodeLookup_bodyShared);
        java.util.List<com.amazon.webservices.awsecommerceservice.BrowseNodeLookupRequest> _browseNodeLookup_bodyRequest = new java.util.ArrayList<com.amazon.webservices.awsecommerceservice.BrowseNodeLookupRequest>();
        com.amazon.webservices.awsecommerceservice.BrowseNodeLookupRequest _browseNodeLookup_bodyRequestVal1 = new com.amazon.webservices.awsecommerceservice.BrowseNodeLookupRequest();
        java.util.List<java.lang.String> _browseNodeLookup_bodyRequestVal1BrowseNodeId = new java.util.ArrayList<java.lang.String>();
        _browseNodeLookup_bodyRequestVal1.getBrowseNodeId().addAll(_browseNodeLookup_bodyRequestVal1BrowseNodeId);
        java.util.List<java.lang.String> _browseNodeLookup_bodyRequestVal1ResponseGroup = new java.util.ArrayList<java.lang.String>();
        _browseNodeLookup_bodyRequestVal1.getResponseGroup().addAll(_browseNodeLookup_bodyRequestVal1ResponseGroup);
        _browseNodeLookup_bodyRequest.add(_browseNodeLookup_bodyRequestVal1);
        _browseNodeLookup_body.getRequest().addAll(_browseNodeLookup_bodyRequest);
        com.amazon.webservices.awsecommerceservice.BrowseNodeLookupResponse _browseNodeLookup__return = port.browseNodeLookup(_browseNodeLookup_body);
        System.out.println("browseNodeLookup.result=" + _browseNodeLookup__return);


        }
        {
        System.out.println("Invoking cartGet...");
        com.amazon.webservices.awsecommerceservice.CartGet _cartGet_body = new com.amazon.webservices.awsecommerceservice.CartGet();
        _cartGet_body.setMarketplaceDomain("MarketplaceDomain1798103290");
        _cartGet_body.setAWSAccessKeyId("AWSAccessKeyId-766149614");
        _cartGet_body.setAssociateTag("AssociateTag1816905320");
        _cartGet_body.setValidate("Validate-1432529954");
        _cartGet_body.setXMLEscaping("XMLEscaping1868046218");
        com.amazon.webservices.awsecommerceservice.CartGetRequest _cartGet_bodyShared = new com.amazon.webservices.awsecommerceservice.CartGetRequest();
        _cartGet_bodyShared.setCartId("CartId1607549838");
        _cartGet_bodyShared.setHMAC("HMAC969517020");
        _cartGet_bodyShared.setMergeCart("MergeCart-1963303319");
        java.util.List<java.lang.String> _cartGet_bodySharedResponseGroup = new java.util.ArrayList<java.lang.String>();
        java.lang.String _cartGet_bodySharedResponseGroupVal1 = "_cartGet_bodySharedResponseGroupVal-1368581460";
        _cartGet_bodySharedResponseGroup.add(_cartGet_bodySharedResponseGroupVal1);
        _cartGet_bodyShared.getResponseGroup().addAll(_cartGet_bodySharedResponseGroup);
        _cartGet_body.setShared(_cartGet_bodyShared);
        java.util.List<com.amazon.webservices.awsecommerceservice.CartGetRequest> _cartGet_bodyRequest = new java.util.ArrayList<com.amazon.webservices.awsecommerceservice.CartGetRequest>();
        com.amazon.webservices.awsecommerceservice.CartGetRequest _cartGet_bodyRequestVal1 = new com.amazon.webservices.awsecommerceservice.CartGetRequest();
        _cartGet_bodyRequestVal1.setCartId("CartId-2077128177");
        _cartGet_bodyRequestVal1.setHMAC("HMAC863221746");
        _cartGet_bodyRequestVal1.setMergeCart("MergeCart-674242118");
        java.util.List<java.lang.String> _cartGet_bodyRequestVal1ResponseGroup = new java.util.ArrayList<java.lang.String>();
        _cartGet_bodyRequestVal1.getResponseGroup().addAll(_cartGet_bodyRequestVal1ResponseGroup);
        _cartGet_bodyRequest.add(_cartGet_bodyRequestVal1);
        _cartGet_body.getRequest().addAll(_cartGet_bodyRequest);
        com.amazon.webservices.awsecommerceservice.CartGetResponse _cartGet__return = port.cartGet(_cartGet_body);
        System.out.println("cartGet.result=" + _cartGet__return);


        }
        {
        System.out.println("Invoking cartModify...");
        com.amazon.webservices.awsecommerceservice.CartModify _cartModify_body = new com.amazon.webservices.awsecommerceservice.CartModify();
        _cartModify_body.setMarketplaceDomain("MarketplaceDomain1759336099");
        _cartModify_body.setAWSAccessKeyId("AWSAccessKeyId-1496052728");
        _cartModify_body.setAssociateTag("AssociateTag2129475500");
        _cartModify_body.setValidate("Validate123222864");
        _cartModify_body.setXMLEscaping("XMLEscaping216933613");
        com.amazon.webservices.awsecommerceservice.CartModifyRequest _cartModify_bodyShared = new com.amazon.webservices.awsecommerceservice.CartModifyRequest();
        _cartModify_bodyShared.setCartId("CartId728212427");
        _cartModify_bodyShared.setHMAC("HMAC2027231721");
        _cartModify_bodyShared.setMergeCart("MergeCart-1821009894");
        com.amazon.webservices.awsecommerceservice.CartModifyRequest.Items _cartModify_bodySharedItems = new com.amazon.webservices.awsecommerceservice.CartModifyRequest.Items();
        java.util.List<com.amazon.webservices.awsecommerceservice.CartModifyRequest.Items.Item> _cartModify_bodySharedItemsItem = new java.util.ArrayList<com.amazon.webservices.awsecommerceservice.CartModifyRequest.Items.Item>();
        _cartModify_bodySharedItems.getItem().addAll(_cartModify_bodySharedItemsItem);
        _cartModify_bodyShared.setItems(_cartModify_bodySharedItems);
        java.util.List<java.lang.String> _cartModify_bodySharedResponseGroup = new java.util.ArrayList<java.lang.String>();
        java.lang.String _cartModify_bodySharedResponseGroupVal1 = "_cartModify_bodySharedResponseGroupVal-1846849521";
        _cartModify_bodySharedResponseGroup.add(_cartModify_bodySharedResponseGroupVal1);
        _cartModify_bodyShared.getResponseGroup().addAll(_cartModify_bodySharedResponseGroup);
        _cartModify_body.setShared(_cartModify_bodyShared);
        java.util.List<com.amazon.webservices.awsecommerceservice.CartModifyRequest> _cartModify_bodyRequest = new java.util.ArrayList<com.amazon.webservices.awsecommerceservice.CartModifyRequest>();
        com.amazon.webservices.awsecommerceservice.CartModifyRequest _cartModify_bodyRequestVal1 = new com.amazon.webservices.awsecommerceservice.CartModifyRequest();
        _cartModify_bodyRequestVal1.setCartId("CartId495027190");
        _cartModify_bodyRequestVal1.setHMAC("HMAC1355030213");
        _cartModify_bodyRequestVal1.setMergeCart("MergeCart-1448118778");
        com.amazon.webservices.awsecommerceservice.CartModifyRequest.Items _cartModify_bodyRequestVal1Items = new com.amazon.webservices.awsecommerceservice.CartModifyRequest.Items();
        java.util.List<com.amazon.webservices.awsecommerceservice.CartModifyRequest.Items.Item> _cartModify_bodyRequestVal1ItemsItem = new java.util.ArrayList<com.amazon.webservices.awsecommerceservice.CartModifyRequest.Items.Item>();
        _cartModify_bodyRequestVal1Items.getItem().addAll(_cartModify_bodyRequestVal1ItemsItem);
        _cartModify_bodyRequestVal1.setItems(_cartModify_bodyRequestVal1Items);
        java.util.List<java.lang.String> _cartModify_bodyRequestVal1ResponseGroup = new java.util.ArrayList<java.lang.String>();
        _cartModify_bodyRequestVal1.getResponseGroup().addAll(_cartModify_bodyRequestVal1ResponseGroup);
        _cartModify_bodyRequest.add(_cartModify_bodyRequestVal1);
        _cartModify_body.getRequest().addAll(_cartModify_bodyRequest);
        com.amazon.webservices.awsecommerceservice.CartModifyResponse _cartModify__return = port.cartModify(_cartModify_body);
        System.out.println("cartModify.result=" + _cartModify__return);


        }
        {
        System.out.println("Invoking cartAdd...");
        com.amazon.webservices.awsecommerceservice.CartAdd _cartAdd_body = new com.amazon.webservices.awsecommerceservice.CartAdd();
        _cartAdd_body.setMarketplaceDomain("MarketplaceDomain-168673384");
        _cartAdd_body.setAWSAccessKeyId("AWSAccessKeyId-299424467");
        _cartAdd_body.setAssociateTag("AssociateTag-494485185");
        _cartAdd_body.setValidate("Validate-7460137");
        _cartAdd_body.setXMLEscaping("XMLEscaping125622367");
        com.amazon.webservices.awsecommerceservice.CartAddRequest _cartAdd_bodyShared = new com.amazon.webservices.awsecommerceservice.CartAddRequest();
        _cartAdd_bodyShared.setCartId("CartId-1071850743");
        _cartAdd_bodyShared.setHMAC("HMAC-1235887331");
        _cartAdd_bodyShared.setMergeCart("MergeCart-1675131845");
        com.amazon.webservices.awsecommerceservice.CartAddRequest.Items _cartAdd_bodySharedItems = new com.amazon.webservices.awsecommerceservice.CartAddRequest.Items();
        java.util.List<com.amazon.webservices.awsecommerceservice.CartAddRequest.Items.Item> _cartAdd_bodySharedItemsItem = new java.util.ArrayList<com.amazon.webservices.awsecommerceservice.CartAddRequest.Items.Item>();
        _cartAdd_bodySharedItems.getItem().addAll(_cartAdd_bodySharedItemsItem);
        _cartAdd_bodyShared.setItems(_cartAdd_bodySharedItems);
        java.util.List<java.lang.String> _cartAdd_bodySharedResponseGroup = new java.util.ArrayList<java.lang.String>();
        java.lang.String _cartAdd_bodySharedResponseGroupVal1 = "_cartAdd_bodySharedResponseGroupVal2021891342";
        _cartAdd_bodySharedResponseGroup.add(_cartAdd_bodySharedResponseGroupVal1);
        _cartAdd_bodyShared.getResponseGroup().addAll(_cartAdd_bodySharedResponseGroup);
        _cartAdd_body.setShared(_cartAdd_bodyShared);
        java.util.List<com.amazon.webservices.awsecommerceservice.CartAddRequest> _cartAdd_bodyRequest = new java.util.ArrayList<com.amazon.webservices.awsecommerceservice.CartAddRequest>();
        com.amazon.webservices.awsecommerceservice.CartAddRequest _cartAdd_bodyRequestVal1 = new com.amazon.webservices.awsecommerceservice.CartAddRequest();
        _cartAdd_bodyRequestVal1.setCartId("CartId-1470872497");
        _cartAdd_bodyRequestVal1.setHMAC("HMAC815473420");
        _cartAdd_bodyRequestVal1.setMergeCart("MergeCart961336604");
        com.amazon.webservices.awsecommerceservice.CartAddRequest.Items _cartAdd_bodyRequestVal1Items = new com.amazon.webservices.awsecommerceservice.CartAddRequest.Items();
        java.util.List<com.amazon.webservices.awsecommerceservice.CartAddRequest.Items.Item> _cartAdd_bodyRequestVal1ItemsItem = new java.util.ArrayList<com.amazon.webservices.awsecommerceservice.CartAddRequest.Items.Item>();
        _cartAdd_bodyRequestVal1Items.getItem().addAll(_cartAdd_bodyRequestVal1ItemsItem);
        _cartAdd_bodyRequestVal1.setItems(_cartAdd_bodyRequestVal1Items);
        java.util.List<java.lang.String> _cartAdd_bodyRequestVal1ResponseGroup = new java.util.ArrayList<java.lang.String>();
        _cartAdd_bodyRequestVal1.getResponseGroup().addAll(_cartAdd_bodyRequestVal1ResponseGroup);
        _cartAdd_bodyRequest.add(_cartAdd_bodyRequestVal1);
        _cartAdd_body.getRequest().addAll(_cartAdd_bodyRequest);
        com.amazon.webservices.awsecommerceservice.CartAddResponse _cartAdd__return = port.cartAdd(_cartAdd_body);
        System.out.println("cartAdd.result=" + _cartAdd__return);


        }
        {
        System.out.println("Invoking itemLookup...");
        com.amazon.webservices.awsecommerceservice.ItemLookup _itemLookup_body = new com.amazon.webservices.awsecommerceservice.ItemLookup();
        _itemLookup_body.setMarketplaceDomain("MarketplaceDomain-1065168156");
        _itemLookup_body.setAWSAccessKeyId("AWSAccessKeyId1708460644");
        _itemLookup_body.setAssociateTag("AssociateTag318564618");
        _itemLookup_body.setValidate("Validate620495926");
        _itemLookup_body.setXMLEscaping("XMLEscaping1965469365");
        com.amazon.webservices.awsecommerceservice.ItemLookupRequest _itemLookup_bodyShared = new com.amazon.webservices.awsecommerceservice.ItemLookupRequest();
        _itemLookup_bodyShared.setCondition("Condition-886201344");
        _itemLookup_bodyShared.setIdType("IdType1178514696");
        _itemLookup_bodyShared.setMerchantId("MerchantId2075815913");
        java.util.List<java.lang.String> _itemLookup_bodySharedItemId = new java.util.ArrayList<java.lang.String>();
        java.lang.String _itemLookup_bodySharedItemIdVal1 = "_itemLookup_bodySharedItemIdVal-1424044490";
        _itemLookup_bodySharedItemId.add(_itemLookup_bodySharedItemIdVal1);
        _itemLookup_bodyShared.getItemId().addAll(_itemLookup_bodySharedItemId);
        java.util.List<java.lang.String> _itemLookup_bodySharedResponseGroup = new java.util.ArrayList<java.lang.String>();
        java.lang.String _itemLookup_bodySharedResponseGroupVal1 = "_itemLookup_bodySharedResponseGroupVal-1172238558";
        _itemLookup_bodySharedResponseGroup.add(_itemLookup_bodySharedResponseGroupVal1);
        _itemLookup_bodyShared.getResponseGroup().addAll(_itemLookup_bodySharedResponseGroup);
        _itemLookup_bodyShared.setSearchIndex("SearchIndex490384330");
        _itemLookup_bodyShared.setVariationPage("VariationPage2006563664");
        _itemLookup_bodyShared.setRelatedItemPage("RelatedItemPage1373208951");
        java.util.List<java.lang.String> _itemLookup_bodySharedRelationshipType = new java.util.ArrayList<java.lang.String>();
        java.lang.String _itemLookup_bodySharedRelationshipTypeVal1 = "_itemLookup_bodySharedRelationshipTypeVal-1272859069";
        _itemLookup_bodySharedRelationshipType.add(_itemLookup_bodySharedRelationshipTypeVal1);
        _itemLookup_bodyShared.getRelationshipType().addAll(_itemLookup_bodySharedRelationshipType);
        _itemLookup_bodyShared.setIncludeReviewsSummary("IncludeReviewsSummary-1492001262");
        _itemLookup_bodyShared.setTruncateReviewsAt(new java.math.BigInteger("2217589230458410717027598051167443460"));
        _itemLookup_body.setShared(_itemLookup_bodyShared);
        java.util.List<com.amazon.webservices.awsecommerceservice.ItemLookupRequest> _itemLookup_bodyRequest = new java.util.ArrayList<com.amazon.webservices.awsecommerceservice.ItemLookupRequest>();
        com.amazon.webservices.awsecommerceservice.ItemLookupRequest _itemLookup_bodyRequestVal1 = new com.amazon.webservices.awsecommerceservice.ItemLookupRequest();
        _itemLookup_bodyRequestVal1.setCondition("Condition-202578826");
        _itemLookup_bodyRequestVal1.setIdType("IdType-1494078913");
        _itemLookup_bodyRequestVal1.setMerchantId("MerchantId587067086");
        java.util.List<java.lang.String> _itemLookup_bodyRequestVal1ItemId = new java.util.ArrayList<java.lang.String>();
        _itemLookup_bodyRequestVal1.getItemId().addAll(_itemLookup_bodyRequestVal1ItemId);
        java.util.List<java.lang.String> _itemLookup_bodyRequestVal1ResponseGroup = new java.util.ArrayList<java.lang.String>();
        _itemLookup_bodyRequestVal1.getResponseGroup().addAll(_itemLookup_bodyRequestVal1ResponseGroup);
        _itemLookup_bodyRequestVal1.setSearchIndex("SearchIndex-1096780117");
        _itemLookup_bodyRequestVal1.setVariationPage("VariationPage1310631740");
        _itemLookup_bodyRequestVal1.setRelatedItemPage("RelatedItemPage1594246385");
        java.util.List<java.lang.String> _itemLookup_bodyRequestVal1RelationshipType = new java.util.ArrayList<java.lang.String>();
        _itemLookup_bodyRequestVal1.getRelationshipType().addAll(_itemLookup_bodyRequestVal1RelationshipType);
        _itemLookup_bodyRequestVal1.setIncludeReviewsSummary("IncludeReviewsSummary-1254772759");
        _itemLookup_bodyRequestVal1.setTruncateReviewsAt(new java.math.BigInteger("11517275929991451312617081217763129972"));
        _itemLookup_bodyRequest.add(_itemLookup_bodyRequestVal1);
        _itemLookup_body.getRequest().addAll(_itemLookup_bodyRequest);
        com.amazon.webservices.awsecommerceservice.ItemLookupResponse _itemLookup__return = port.itemLookup(_itemLookup_body);
        System.out.println("itemLookup.result=" + _itemLookup__return);


        }
        {
        System.out.println("Invoking similarityLookup...");
        com.amazon.webservices.awsecommerceservice.SimilarityLookup _similarityLookup_body = new com.amazon.webservices.awsecommerceservice.SimilarityLookup();
        _similarityLookup_body.setMarketplaceDomain("MarketplaceDomain1645795707");
        _similarityLookup_body.setAWSAccessKeyId("AWSAccessKeyId133051750");
        _similarityLookup_body.setAssociateTag("AssociateTag1992838748");
        _similarityLookup_body.setValidate("Validate1705101415");
        _similarityLookup_body.setXMLEscaping("XMLEscaping-1635554515");
        com.amazon.webservices.awsecommerceservice.SimilarityLookupRequest _similarityLookup_bodyShared = new com.amazon.webservices.awsecommerceservice.SimilarityLookupRequest();
        _similarityLookup_bodyShared.setCondition("Condition1059113860");
        java.util.List<java.lang.String> _similarityLookup_bodySharedItemId = new java.util.ArrayList<java.lang.String>();
        java.lang.String _similarityLookup_bodySharedItemIdVal1 = "_similarityLookup_bodySharedItemIdVal-242912083";
        _similarityLookup_bodySharedItemId.add(_similarityLookup_bodySharedItemIdVal1);
        _similarityLookup_bodyShared.getItemId().addAll(_similarityLookup_bodySharedItemId);
        _similarityLookup_bodyShared.setMerchantId("MerchantId2090830108");
        java.util.List<java.lang.String> _similarityLookup_bodySharedResponseGroup = new java.util.ArrayList<java.lang.String>();
        java.lang.String _similarityLookup_bodySharedResponseGroupVal1 = "_similarityLookup_bodySharedResponseGroupVal514098123";
        _similarityLookup_bodySharedResponseGroup.add(_similarityLookup_bodySharedResponseGroupVal1);
        _similarityLookup_bodyShared.getResponseGroup().addAll(_similarityLookup_bodySharedResponseGroup);
        _similarityLookup_bodyShared.setSimilarityType("SimilarityType-103615394");
        _similarityLookup_body.setShared(_similarityLookup_bodyShared);
        java.util.List<com.amazon.webservices.awsecommerceservice.SimilarityLookupRequest> _similarityLookup_bodyRequest = new java.util.ArrayList<com.amazon.webservices.awsecommerceservice.SimilarityLookupRequest>();
        com.amazon.webservices.awsecommerceservice.SimilarityLookupRequest _similarityLookup_bodyRequestVal1 = new com.amazon.webservices.awsecommerceservice.SimilarityLookupRequest();
        _similarityLookup_bodyRequestVal1.setCondition("Condition-1335423592");
        java.util.List<java.lang.String> _similarityLookup_bodyRequestVal1ItemId = new java.util.ArrayList<java.lang.String>();
        _similarityLookup_bodyRequestVal1.getItemId().addAll(_similarityLookup_bodyRequestVal1ItemId);
        _similarityLookup_bodyRequestVal1.setMerchantId("MerchantId-528165838");
        java.util.List<java.lang.String> _similarityLookup_bodyRequestVal1ResponseGroup = new java.util.ArrayList<java.lang.String>();
        _similarityLookup_bodyRequestVal1.getResponseGroup().addAll(_similarityLookup_bodyRequestVal1ResponseGroup);
        _similarityLookup_bodyRequestVal1.setSimilarityType("SimilarityType912536799");
        _similarityLookup_bodyRequest.add(_similarityLookup_bodyRequestVal1);
        _similarityLookup_body.getRequest().addAll(_similarityLookup_bodyRequest);
        com.amazon.webservices.awsecommerceservice.SimilarityLookupResponse _similarityLookup__return = port.similarityLookup(_similarityLookup_body);
        System.out.println("similarityLookup.result=" + _similarityLookup__return);


        }
        {
        System.out.println("Invoking itemSearch...");
        com.amazon.webservices.awsecommerceservice.ItemSearch _itemSearch_body = new com.amazon.webservices.awsecommerceservice.ItemSearch();
        _itemSearch_body.setMarketplaceDomain("MarketplaceDomain-426611286");
        _itemSearch_body.setAWSAccessKeyId("AWSAccessKeyId-846128958");
        _itemSearch_body.setAssociateTag("AssociateTag-193658545");
        _itemSearch_body.setXMLEscaping("XMLEscaping285492746");
        _itemSearch_body.setValidate("Validate-496102456");
        com.amazon.webservices.awsecommerceservice.ItemSearchRequest _itemSearch_bodyShared = new com.amazon.webservices.awsecommerceservice.ItemSearchRequest();
        _itemSearch_bodyShared.setActor("Actor-152548078");
        _itemSearch_bodyShared.setArtist("Artist-1951153754");
        _itemSearch_bodyShared.setAvailability("Availability-1315810196");
        java.util.List<java.lang.String> _itemSearch_bodySharedAudienceRating = new java.util.ArrayList<java.lang.String>();
        java.lang.String _itemSearch_bodySharedAudienceRatingVal1 = "_itemSearch_bodySharedAudienceRatingVal1508972379";
        _itemSearch_bodySharedAudienceRating.add(_itemSearch_bodySharedAudienceRatingVal1);
        _itemSearch_bodyShared.getAudienceRating().addAll(_itemSearch_bodySharedAudienceRating);
        _itemSearch_bodyShared.setAuthor("Author664461498");
        _itemSearch_bodyShared.setBrand("Brand-1471815251");
        _itemSearch_bodyShared.setBrowseNode("BrowseNode894567497");
        _itemSearch_bodyShared.setComposer("Composer-199002084");
        _itemSearch_bodyShared.setCondition("Condition-115389066");
        _itemSearch_bodyShared.setConductor("Conductor-1032850925");
        _itemSearch_bodyShared.setDirector("Director1768302825");
        _itemSearch_bodyShared.setItemPage(new java.math.BigInteger("-435305349069848036289495911401912642"));
        _itemSearch_bodyShared.setKeywords("Keywords174326052");
        _itemSearch_bodyShared.setManufacturer("Manufacturer-1817982406");
        _itemSearch_bodyShared.setMaximumPrice(new java.math.BigInteger("5491975326160700927534910050339724964"));
        _itemSearch_bodyShared.setMerchantId("MerchantId-81681783");
        _itemSearch_bodyShared.setMinimumPrice(new java.math.BigInteger("1422533048725545090861610381131788001"));
        _itemSearch_bodyShared.setMinPercentageOff(new java.math.BigInteger("-4613126986205515192710107947243345129"));
        _itemSearch_bodyShared.setMusicLabel("MusicLabel-1861041958");
        _itemSearch_bodyShared.setOrchestra("Orchestra-2109554648");
        _itemSearch_bodyShared.setPower("Power-264562818");
        _itemSearch_bodyShared.setPublisher("Publisher-84899033");
        _itemSearch_bodyShared.setRelatedItemPage("RelatedItemPage2131542429");
        java.util.List<java.lang.String> _itemSearch_bodySharedRelationshipType = new java.util.ArrayList<java.lang.String>();
        java.lang.String _itemSearch_bodySharedRelationshipTypeVal1 = "_itemSearch_bodySharedRelationshipTypeVal-1741519970";
        _itemSearch_bodySharedRelationshipType.add(_itemSearch_bodySharedRelationshipTypeVal1);
        _itemSearch_bodyShared.getRelationshipType().addAll(_itemSearch_bodySharedRelationshipType);
        java.util.List<java.lang.String> _itemSearch_bodySharedResponseGroup = new java.util.ArrayList<java.lang.String>();
        java.lang.String _itemSearch_bodySharedResponseGroupVal1 = "_itemSearch_bodySharedResponseGroupVal423926223";
        _itemSearch_bodySharedResponseGroup.add(_itemSearch_bodySharedResponseGroupVal1);
        _itemSearch_bodyShared.getResponseGroup().addAll(_itemSearch_bodySharedResponseGroup);
        _itemSearch_bodyShared.setSearchIndex("SearchIndex1646657778");
        _itemSearch_bodyShared.setSort("Sort284013088");
        _itemSearch_bodyShared.setTitle("Title1522301149");
        _itemSearch_bodyShared.setReleaseDate("ReleaseDate-1420309191");
        _itemSearch_bodyShared.setIncludeReviewsSummary("IncludeReviewsSummary-1418809551");
        _itemSearch_bodyShared.setTruncateReviewsAt(new java.math.BigInteger("-31596094657980792645959349285332604838"));
        _itemSearch_body.setShared(_itemSearch_bodyShared);
        java.util.List<com.amazon.webservices.awsecommerceservice.ItemSearchRequest> _itemSearch_bodyRequest = new java.util.ArrayList<com.amazon.webservices.awsecommerceservice.ItemSearchRequest>();
        com.amazon.webservices.awsecommerceservice.ItemSearchRequest _itemSearch_bodyRequestVal1 = new com.amazon.webservices.awsecommerceservice.ItemSearchRequest();
        _itemSearch_bodyRequestVal1.setActor("Actor-1561400355");
        _itemSearch_bodyRequestVal1.setArtist("Artist-451471169");
        _itemSearch_bodyRequestVal1.setAvailability("Availability1631208134");
        java.util.List<java.lang.String> _itemSearch_bodyRequestVal1AudienceRating = new java.util.ArrayList<java.lang.String>();
        _itemSearch_bodyRequestVal1.getAudienceRating().addAll(_itemSearch_bodyRequestVal1AudienceRating);
        _itemSearch_bodyRequestVal1.setAuthor("Author445986963");
        _itemSearch_bodyRequestVal1.setBrand("Brand1455893616");
        _itemSearch_bodyRequestVal1.setBrowseNode("BrowseNode-301793725");
        _itemSearch_bodyRequestVal1.setComposer("Composer1811574155");
        _itemSearch_bodyRequestVal1.setCondition("Condition-255718033");
        _itemSearch_bodyRequestVal1.setConductor("Conductor-861990276");
        _itemSearch_bodyRequestVal1.setDirector("Director-103974468");
        _itemSearch_bodyRequestVal1.setItemPage(new java.math.BigInteger("83333623814956581997988923888582722287"));
        _itemSearch_bodyRequestVal1.setKeywords("Keywords-110849349");
        _itemSearch_bodyRequestVal1.setManufacturer("Manufacturer1385893314");
        _itemSearch_bodyRequestVal1.setMaximumPrice(new java.math.BigInteger("57600704275286364392585248963029591545"));
        _itemSearch_bodyRequestVal1.setMerchantId("MerchantId-970266346");
        _itemSearch_bodyRequestVal1.setMinimumPrice(new java.math.BigInteger("36243269398027674323418790923793699783"));
        _itemSearch_bodyRequestVal1.setMinPercentageOff(new java.math.BigInteger("2838209952788964223651639958173230145"));
        _itemSearch_bodyRequestVal1.setMusicLabel("MusicLabel1232136310");
        _itemSearch_bodyRequestVal1.setOrchestra("Orchestra-846142254");
        _itemSearch_bodyRequestVal1.setPower("Power-566551342");
        _itemSearch_bodyRequestVal1.setPublisher("Publisher-1662718497");
        _itemSearch_bodyRequestVal1.setRelatedItemPage("RelatedItemPage1924182174");
        java.util.List<java.lang.String> _itemSearch_bodyRequestVal1RelationshipType = new java.util.ArrayList<java.lang.String>();
        _itemSearch_bodyRequestVal1.getRelationshipType().addAll(_itemSearch_bodyRequestVal1RelationshipType);
        java.util.List<java.lang.String> _itemSearch_bodyRequestVal1ResponseGroup = new java.util.ArrayList<java.lang.String>();
        _itemSearch_bodyRequestVal1.getResponseGroup().addAll(_itemSearch_bodyRequestVal1ResponseGroup);
        _itemSearch_bodyRequestVal1.setSearchIndex("SearchIndex2123135049");
        _itemSearch_bodyRequestVal1.setSort("Sort-1326017524");
        _itemSearch_bodyRequestVal1.setTitle("Title-1822661984");
        _itemSearch_bodyRequestVal1.setReleaseDate("ReleaseDate-328402043");
        _itemSearch_bodyRequestVal1.setIncludeReviewsSummary("IncludeReviewsSummary1061918208");
        _itemSearch_bodyRequestVal1.setTruncateReviewsAt(new java.math.BigInteger("-52656634755183957845332641790151854962"));
        _itemSearch_bodyRequest.add(_itemSearch_bodyRequestVal1);
        _itemSearch_body.getRequest().addAll(_itemSearch_bodyRequest);
        com.amazon.webservices.awsecommerceservice.ItemSearchResponse _itemSearch__return = port.itemSearch(_itemSearch_body);
        System.out.println("itemSearch.result=" + _itemSearch__return);


        }
        {
        System.out.println("Invoking cartClear...");
        com.amazon.webservices.awsecommerceservice.CartClear _cartClear_body = new com.amazon.webservices.awsecommerceservice.CartClear();
        _cartClear_body.setMarketplaceDomain("MarketplaceDomain-995248196");
        _cartClear_body.setAWSAccessKeyId("AWSAccessKeyId-1521528011");
        _cartClear_body.setAssociateTag("AssociateTag-1843538451");
        _cartClear_body.setValidate("Validate-1301377799");
        _cartClear_body.setXMLEscaping("XMLEscaping-1078380678");
        com.amazon.webservices.awsecommerceservice.CartClearRequest _cartClear_bodyShared = new com.amazon.webservices.awsecommerceservice.CartClearRequest();
        _cartClear_bodyShared.setCartId("CartId830234400");
        _cartClear_bodyShared.setHMAC("HMAC1482680831");
        _cartClear_bodyShared.setMergeCart("MergeCart321543061");
        java.util.List<java.lang.String> _cartClear_bodySharedResponseGroup = new java.util.ArrayList<java.lang.String>();
        java.lang.String _cartClear_bodySharedResponseGroupVal1 = "_cartClear_bodySharedResponseGroupVal120576707";
        _cartClear_bodySharedResponseGroup.add(_cartClear_bodySharedResponseGroupVal1);
        _cartClear_bodyShared.getResponseGroup().addAll(_cartClear_bodySharedResponseGroup);
        _cartClear_body.setShared(_cartClear_bodyShared);
        java.util.List<com.amazon.webservices.awsecommerceservice.CartClearRequest> _cartClear_bodyRequest = new java.util.ArrayList<com.amazon.webservices.awsecommerceservice.CartClearRequest>();
        com.amazon.webservices.awsecommerceservice.CartClearRequest _cartClear_bodyRequestVal1 = new com.amazon.webservices.awsecommerceservice.CartClearRequest();
        _cartClear_bodyRequestVal1.setCartId("CartId975497823");
        _cartClear_bodyRequestVal1.setHMAC("HMAC-455622692");
        _cartClear_bodyRequestVal1.setMergeCart("MergeCart-1601895700");
        java.util.List<java.lang.String> _cartClear_bodyRequestVal1ResponseGroup = new java.util.ArrayList<java.lang.String>();
        _cartClear_bodyRequestVal1.getResponseGroup().addAll(_cartClear_bodyRequestVal1ResponseGroup);
        _cartClear_bodyRequest.add(_cartClear_bodyRequestVal1);
        _cartClear_body.getRequest().addAll(_cartClear_bodyRequest);
        com.amazon.webservices.awsecommerceservice.CartClearResponse _cartClear__return = port.cartClear(_cartClear_body);
        System.out.println("cartClear.result=" + _cartClear__return);


        }

        System.exit(0);
    }

}
